/* Automatically generated by
	VMPluginCodeGenerator VMMaker.oscog-eem.3173 uuid: 87232128-51b6-437d-bff1-7c0965872696
   from
	ArrayBulkPlugin * RawBitsBulkPlugins-Plugins-tonel.1 uuid: 3f99f3d2-2860-4a13-9374-1db9a7115122
 */
static char __buildInfo[] = "ArrayBulkPlugin * RawBitsBulkPlugins-Plugins-tonel.1 uuid: 3f99f3d2-2860-4a13-9374-1db9a7115122 " __DATE__ ;


#include "config.h"
#include <math.h>
#include "sqMathShim.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#include "sqMemoryAccess.h"

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
# define INT_EXT "(i)"
#else
# define INT_EXT "(e)"
#endif


/*** Function Prototypes ***/
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut10(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut11(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut12(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut13(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut14(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut2(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut3(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut4(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut5(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut6(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut7(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut8(void);
EXPORT(sqInt) primitiveFloat32StartingAtPut9(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut10(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut11(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut12(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut13(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut14(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut2(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut3(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut4(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut5(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut6(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut7(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut8(void);
EXPORT(sqInt) primitiveFloat64StartingAtPut9(void);
EXPORT(sqInt) primitiveInt32StartingAtPut10(void);
EXPORT(sqInt) primitiveInt32StartingAtPut11(void);
EXPORT(sqInt) primitiveInt32StartingAtPut12(void);
EXPORT(sqInt) primitiveInt32StartingAtPut13(void);
EXPORT(sqInt) primitiveInt32StartingAtPut14(void);
EXPORT(sqInt) primitiveInt32StartingAtPut2(void);
EXPORT(sqInt) primitiveInt32StartingAtPut3(void);
EXPORT(sqInt) primitiveInt32StartingAtPut4(void);
EXPORT(sqInt) primitiveInt32StartingAtPut5(void);
EXPORT(sqInt) primitiveInt32StartingAtPut6(void);
EXPORT(sqInt) primitiveInt32StartingAtPut7(void);
EXPORT(sqInt) primitiveInt32StartingAtPut8(void);
EXPORT(sqInt) primitiveInt32StartingAtPut9(void);
EXPORT(sqInt) primitiveInt64StartingAtPut10(void);
EXPORT(sqInt) primitiveInt64StartingAtPut11(void);
EXPORT(sqInt) primitiveInt64StartingAtPut12(void);
EXPORT(sqInt) primitiveInt64StartingAtPut13(void);
EXPORT(sqInt) primitiveInt64StartingAtPut14(void);
EXPORT(sqInt) primitiveInt64StartingAtPut2(void);
EXPORT(sqInt) primitiveInt64StartingAtPut3(void);
EXPORT(sqInt) primitiveInt64StartingAtPut4(void);
EXPORT(sqInt) primitiveInt64StartingAtPut5(void);
EXPORT(sqInt) primitiveInt64StartingAtPut6(void);
EXPORT(sqInt) primitiveInt64StartingAtPut7(void);
EXPORT(sqInt) primitiveInt64StartingAtPut8(void);
EXPORT(sqInt) primitiveInt64StartingAtPut9(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut10(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut11(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut12(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut13(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut14(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut2(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut3(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut4(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut5(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut6(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut7(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut8(void);
EXPORT(sqInt) primitiveUInt32StartingAtPut9(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut10(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut11(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut12(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut13(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut14(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut2(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut3(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut4(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut5(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut6(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut7(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut8(void);
EXPORT(sqInt) primitiveUInt64StartingAtPut9(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine *anInterpreter);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*failed)(void);
static void * (*firstIndexableField)(sqInt oop);
static sqInt (*isLong64s)(sqInt oop);
static sqInt (*isWords)(sqInt oop);
static sqInt (*pop)(sqInt nItems);
static sqInt (*primitiveFailFor)(sqInt reasonCode);
static sqInt (*slotSizeOf)(sqInt oop);
static double (*stackFloatValue)(sqInt offset);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt failed(void);
extern void * firstIndexableField(sqInt oop);
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 17)
extern sqInt isLong64s(sqInt oop);
#else
# define isLong64s(oop) 0
#endif
extern sqInt isWords(sqInt oop);
extern sqInt pop(sqInt nItems);
extern sqInt primitiveFailFor(sqInt reasonCode);
extern sqInt slotSizeOf(sqInt oop);
extern double stackFloatValue(sqInt offset);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName = "ArrayBulkPlugin * RawBitsBulkPlugins-Plugins-tonel.1 " INT_EXT;



/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut10 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut10(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(11);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(10)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 10) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(9));
	slotPtr[startSlot + 1] = (stackFloatValue(8));
	slotPtr[startSlot + 2] = (stackFloatValue(7));
	slotPtr[startSlot + 3] = (stackFloatValue(6));
	slotPtr[startSlot + 4] = (stackFloatValue(5));
	slotPtr[startSlot + 5] = (stackFloatValue(4));
	slotPtr[startSlot + 6] = (stackFloatValue(3));
	slotPtr[startSlot + 7] = (stackFloatValue(2));
	slotPtr[startSlot + 8] = (stackFloatValue(1));
	slotPtr[startSlot + 9] = (stackFloatValue(0));
	pop(11);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut11 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut11(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(12);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(11)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 11) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(10));
	slotPtr[startSlot + 1] = (stackFloatValue(9));
	slotPtr[startSlot + 2] = (stackFloatValue(8));
	slotPtr[startSlot + 3] = (stackFloatValue(7));
	slotPtr[startSlot + 4] = (stackFloatValue(6));
	slotPtr[startSlot + 5] = (stackFloatValue(5));
	slotPtr[startSlot + 6] = (stackFloatValue(4));
	slotPtr[startSlot + 7] = (stackFloatValue(3));
	slotPtr[startSlot + 8] = (stackFloatValue(2));
	slotPtr[startSlot + 9] = (stackFloatValue(1));
	slotPtr[startSlot + 10] = (stackFloatValue(0));
	pop(12);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut12 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut12(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(13);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(12)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 12) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(11));
	slotPtr[startSlot + 1] = (stackFloatValue(10));
	slotPtr[startSlot + 2] = (stackFloatValue(9));
	slotPtr[startSlot + 3] = (stackFloatValue(8));
	slotPtr[startSlot + 4] = (stackFloatValue(7));
	slotPtr[startSlot + 5] = (stackFloatValue(6));
	slotPtr[startSlot + 6] = (stackFloatValue(5));
	slotPtr[startSlot + 7] = (stackFloatValue(4));
	slotPtr[startSlot + 8] = (stackFloatValue(3));
	slotPtr[startSlot + 9] = (stackFloatValue(2));
	slotPtr[startSlot + 10] = (stackFloatValue(1));
	slotPtr[startSlot + 11] = (stackFloatValue(0));
	pop(13);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut13 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut13(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(14);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(13)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 13) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(12));
	slotPtr[startSlot + 1] = (stackFloatValue(11));
	slotPtr[startSlot + 2] = (stackFloatValue(10));
	slotPtr[startSlot + 3] = (stackFloatValue(9));
	slotPtr[startSlot + 4] = (stackFloatValue(8));
	slotPtr[startSlot + 5] = (stackFloatValue(7));
	slotPtr[startSlot + 6] = (stackFloatValue(6));
	slotPtr[startSlot + 7] = (stackFloatValue(5));
	slotPtr[startSlot + 8] = (stackFloatValue(4));
	slotPtr[startSlot + 9] = (stackFloatValue(3));
	slotPtr[startSlot + 10] = (stackFloatValue(2));
	slotPtr[startSlot + 11] = (stackFloatValue(1));
	slotPtr[startSlot + 12] = (stackFloatValue(0));
	pop(14);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut14 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut14(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(15);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(14)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 14) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(13));
	slotPtr[startSlot + 1] = (stackFloatValue(12));
	slotPtr[startSlot + 2] = (stackFloatValue(11));
	slotPtr[startSlot + 3] = (stackFloatValue(10));
	slotPtr[startSlot + 4] = (stackFloatValue(9));
	slotPtr[startSlot + 5] = (stackFloatValue(8));
	slotPtr[startSlot + 6] = (stackFloatValue(7));
	slotPtr[startSlot + 7] = (stackFloatValue(6));
	slotPtr[startSlot + 8] = (stackFloatValue(5));
	slotPtr[startSlot + 9] = (stackFloatValue(4));
	slotPtr[startSlot + 10] = (stackFloatValue(3));
	slotPtr[startSlot + 11] = (stackFloatValue(2));
	slotPtr[startSlot + 12] = (stackFloatValue(1));
	slotPtr[startSlot + 13] = (stackFloatValue(0));
	pop(15);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut2 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut2(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(3);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(2)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 2) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(1));
	slotPtr[startSlot + 1] = (stackFloatValue(0));
	pop(3);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut3 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut3(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(4);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(3)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 3) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(2));
	slotPtr[startSlot + 1] = (stackFloatValue(1));
	slotPtr[startSlot + 2] = (stackFloatValue(0));
	pop(4);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut4 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut4(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(5);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(4)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 4) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(3));
	slotPtr[startSlot + 1] = (stackFloatValue(2));
	slotPtr[startSlot + 2] = (stackFloatValue(1));
	slotPtr[startSlot + 3] = (stackFloatValue(0));
	pop(5);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut5 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut5(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(6);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(5)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 5) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(4));
	slotPtr[startSlot + 1] = (stackFloatValue(3));
	slotPtr[startSlot + 2] = (stackFloatValue(2));
	slotPtr[startSlot + 3] = (stackFloatValue(1));
	slotPtr[startSlot + 4] = (stackFloatValue(0));
	pop(6);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut6 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut6(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(7);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(6)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 6) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(5));
	slotPtr[startSlot + 1] = (stackFloatValue(4));
	slotPtr[startSlot + 2] = (stackFloatValue(3));
	slotPtr[startSlot + 3] = (stackFloatValue(2));
	slotPtr[startSlot + 4] = (stackFloatValue(1));
	slotPtr[startSlot + 5] = (stackFloatValue(0));
	pop(7);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut7 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut7(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(8);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(7)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 7) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(6));
	slotPtr[startSlot + 1] = (stackFloatValue(5));
	slotPtr[startSlot + 2] = (stackFloatValue(4));
	slotPtr[startSlot + 3] = (stackFloatValue(3));
	slotPtr[startSlot + 4] = (stackFloatValue(2));
	slotPtr[startSlot + 5] = (stackFloatValue(1));
	slotPtr[startSlot + 6] = (stackFloatValue(0));
	pop(8);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut8 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut8(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(9);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(8)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 8) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(7));
	slotPtr[startSlot + 1] = (stackFloatValue(6));
	slotPtr[startSlot + 2] = (stackFloatValue(5));
	slotPtr[startSlot + 3] = (stackFloatValue(4));
	slotPtr[startSlot + 4] = (stackFloatValue(3));
	slotPtr[startSlot + 5] = (stackFloatValue(2));
	slotPtr[startSlot + 6] = (stackFloatValue(1));
	slotPtr[startSlot + 7] = (stackFloatValue(0));
	pop(9);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat32StartingAtPut9 */
EXPORT(sqInt)
primitiveFloat32StartingAtPut9(void)
{
    sqInt numSlots;
    sqInt rcvr;
    float *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(10);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(9)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 9) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((float *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(8));
	slotPtr[startSlot + 1] = (stackFloatValue(7));
	slotPtr[startSlot + 2] = (stackFloatValue(6));
	slotPtr[startSlot + 3] = (stackFloatValue(5));
	slotPtr[startSlot + 4] = (stackFloatValue(4));
	slotPtr[startSlot + 5] = (stackFloatValue(3));
	slotPtr[startSlot + 6] = (stackFloatValue(2));
	slotPtr[startSlot + 7] = (stackFloatValue(1));
	slotPtr[startSlot + 8] = (stackFloatValue(0));
	pop(10);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut10 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut10(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(11);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(10)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 10) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(9));
	slotPtr[startSlot + 1] = (stackFloatValue(8));
	slotPtr[startSlot + 2] = (stackFloatValue(7));
	slotPtr[startSlot + 3] = (stackFloatValue(6));
	slotPtr[startSlot + 4] = (stackFloatValue(5));
	slotPtr[startSlot + 5] = (stackFloatValue(4));
	slotPtr[startSlot + 6] = (stackFloatValue(3));
	slotPtr[startSlot + 7] = (stackFloatValue(2));
	slotPtr[startSlot + 8] = (stackFloatValue(1));
	slotPtr[startSlot + 9] = (stackFloatValue(0));
	pop(11);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut11 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut11(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(12);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(11)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 11) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(10));
	slotPtr[startSlot + 1] = (stackFloatValue(9));
	slotPtr[startSlot + 2] = (stackFloatValue(8));
	slotPtr[startSlot + 3] = (stackFloatValue(7));
	slotPtr[startSlot + 4] = (stackFloatValue(6));
	slotPtr[startSlot + 5] = (stackFloatValue(5));
	slotPtr[startSlot + 6] = (stackFloatValue(4));
	slotPtr[startSlot + 7] = (stackFloatValue(3));
	slotPtr[startSlot + 8] = (stackFloatValue(2));
	slotPtr[startSlot + 9] = (stackFloatValue(1));
	slotPtr[startSlot + 10] = (stackFloatValue(0));
	pop(12);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut12 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut12(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(13);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(12)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 12) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(11));
	slotPtr[startSlot + 1] = (stackFloatValue(10));
	slotPtr[startSlot + 2] = (stackFloatValue(9));
	slotPtr[startSlot + 3] = (stackFloatValue(8));
	slotPtr[startSlot + 4] = (stackFloatValue(7));
	slotPtr[startSlot + 5] = (stackFloatValue(6));
	slotPtr[startSlot + 6] = (stackFloatValue(5));
	slotPtr[startSlot + 7] = (stackFloatValue(4));
	slotPtr[startSlot + 8] = (stackFloatValue(3));
	slotPtr[startSlot + 9] = (stackFloatValue(2));
	slotPtr[startSlot + 10] = (stackFloatValue(1));
	slotPtr[startSlot + 11] = (stackFloatValue(0));
	pop(13);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut13 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut13(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(14);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(13)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 13) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(12));
	slotPtr[startSlot + 1] = (stackFloatValue(11));
	slotPtr[startSlot + 2] = (stackFloatValue(10));
	slotPtr[startSlot + 3] = (stackFloatValue(9));
	slotPtr[startSlot + 4] = (stackFloatValue(8));
	slotPtr[startSlot + 5] = (stackFloatValue(7));
	slotPtr[startSlot + 6] = (stackFloatValue(6));
	slotPtr[startSlot + 7] = (stackFloatValue(5));
	slotPtr[startSlot + 8] = (stackFloatValue(4));
	slotPtr[startSlot + 9] = (stackFloatValue(3));
	slotPtr[startSlot + 10] = (stackFloatValue(2));
	slotPtr[startSlot + 11] = (stackFloatValue(1));
	slotPtr[startSlot + 12] = (stackFloatValue(0));
	pop(14);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut14 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut14(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(15);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(14)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 14) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(13));
	slotPtr[startSlot + 1] = (stackFloatValue(12));
	slotPtr[startSlot + 2] = (stackFloatValue(11));
	slotPtr[startSlot + 3] = (stackFloatValue(10));
	slotPtr[startSlot + 4] = (stackFloatValue(9));
	slotPtr[startSlot + 5] = (stackFloatValue(8));
	slotPtr[startSlot + 6] = (stackFloatValue(7));
	slotPtr[startSlot + 7] = (stackFloatValue(6));
	slotPtr[startSlot + 8] = (stackFloatValue(5));
	slotPtr[startSlot + 9] = (stackFloatValue(4));
	slotPtr[startSlot + 10] = (stackFloatValue(3));
	slotPtr[startSlot + 11] = (stackFloatValue(2));
	slotPtr[startSlot + 12] = (stackFloatValue(1));
	slotPtr[startSlot + 13] = (stackFloatValue(0));
	pop(15);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut2 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut2(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(3);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(2)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 2) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(1));
	slotPtr[startSlot + 1] = (stackFloatValue(0));
	pop(3);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut3 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut3(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(4);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(3)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 3) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(2));
	slotPtr[startSlot + 1] = (stackFloatValue(1));
	slotPtr[startSlot + 2] = (stackFloatValue(0));
	pop(4);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut4 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut4(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(5);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(4)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 4) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(3));
	slotPtr[startSlot + 1] = (stackFloatValue(2));
	slotPtr[startSlot + 2] = (stackFloatValue(1));
	slotPtr[startSlot + 3] = (stackFloatValue(0));
	pop(5);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut5 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut5(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(6);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(5)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 5) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(4));
	slotPtr[startSlot + 1] = (stackFloatValue(3));
	slotPtr[startSlot + 2] = (stackFloatValue(2));
	slotPtr[startSlot + 3] = (stackFloatValue(1));
	slotPtr[startSlot + 4] = (stackFloatValue(0));
	pop(6);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut6 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut6(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(7);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(6)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 6) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(5));
	slotPtr[startSlot + 1] = (stackFloatValue(4));
	slotPtr[startSlot + 2] = (stackFloatValue(3));
	slotPtr[startSlot + 3] = (stackFloatValue(2));
	slotPtr[startSlot + 4] = (stackFloatValue(1));
	slotPtr[startSlot + 5] = (stackFloatValue(0));
	pop(7);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut7 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut7(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(8);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(7)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 7) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(6));
	slotPtr[startSlot + 1] = (stackFloatValue(5));
	slotPtr[startSlot + 2] = (stackFloatValue(4));
	slotPtr[startSlot + 3] = (stackFloatValue(3));
	slotPtr[startSlot + 4] = (stackFloatValue(2));
	slotPtr[startSlot + 5] = (stackFloatValue(1));
	slotPtr[startSlot + 6] = (stackFloatValue(0));
	pop(8);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut8 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut8(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(9);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(8)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 8) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(7));
	slotPtr[startSlot + 1] = (stackFloatValue(6));
	slotPtr[startSlot + 2] = (stackFloatValue(5));
	slotPtr[startSlot + 3] = (stackFloatValue(4));
	slotPtr[startSlot + 4] = (stackFloatValue(3));
	slotPtr[startSlot + 5] = (stackFloatValue(2));
	slotPtr[startSlot + 6] = (stackFloatValue(1));
	slotPtr[startSlot + 7] = (stackFloatValue(0));
	pop(9);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveFloat64StartingAtPut9 */
EXPORT(sqInt)
primitiveFloat64StartingAtPut9(void)
{
    sqInt numSlots;
    sqInt rcvr;
    double *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(10);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(9)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 9) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((double *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackFloatValue(8));
	slotPtr[startSlot + 1] = (stackFloatValue(7));
	slotPtr[startSlot + 2] = (stackFloatValue(6));
	slotPtr[startSlot + 3] = (stackFloatValue(5));
	slotPtr[startSlot + 4] = (stackFloatValue(4));
	slotPtr[startSlot + 5] = (stackFloatValue(3));
	slotPtr[startSlot + 6] = (stackFloatValue(2));
	slotPtr[startSlot + 7] = (stackFloatValue(1));
	slotPtr[startSlot + 8] = (stackFloatValue(0));
	pop(10);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut10 */
EXPORT(sqInt)
primitiveInt32StartingAtPut10(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(11);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(10)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 10) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(9));
	slotPtr[startSlot + 1] = (stackIntegerValue(8));
	slotPtr[startSlot + 2] = (stackIntegerValue(7));
	slotPtr[startSlot + 3] = (stackIntegerValue(6));
	slotPtr[startSlot + 4] = (stackIntegerValue(5));
	slotPtr[startSlot + 5] = (stackIntegerValue(4));
	slotPtr[startSlot + 6] = (stackIntegerValue(3));
	slotPtr[startSlot + 7] = (stackIntegerValue(2));
	slotPtr[startSlot + 8] = (stackIntegerValue(1));
	slotPtr[startSlot + 9] = (stackIntegerValue(0));
	pop(11);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut11 */
EXPORT(sqInt)
primitiveInt32StartingAtPut11(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(12);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(11)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 11) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(10));
	slotPtr[startSlot + 1] = (stackIntegerValue(9));
	slotPtr[startSlot + 2] = (stackIntegerValue(8));
	slotPtr[startSlot + 3] = (stackIntegerValue(7));
	slotPtr[startSlot + 4] = (stackIntegerValue(6));
	slotPtr[startSlot + 5] = (stackIntegerValue(5));
	slotPtr[startSlot + 6] = (stackIntegerValue(4));
	slotPtr[startSlot + 7] = (stackIntegerValue(3));
	slotPtr[startSlot + 8] = (stackIntegerValue(2));
	slotPtr[startSlot + 9] = (stackIntegerValue(1));
	slotPtr[startSlot + 10] = (stackIntegerValue(0));
	pop(12);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut12 */
EXPORT(sqInt)
primitiveInt32StartingAtPut12(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(13);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(12)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 12) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(11));
	slotPtr[startSlot + 1] = (stackIntegerValue(10));
	slotPtr[startSlot + 2] = (stackIntegerValue(9));
	slotPtr[startSlot + 3] = (stackIntegerValue(8));
	slotPtr[startSlot + 4] = (stackIntegerValue(7));
	slotPtr[startSlot + 5] = (stackIntegerValue(6));
	slotPtr[startSlot + 6] = (stackIntegerValue(5));
	slotPtr[startSlot + 7] = (stackIntegerValue(4));
	slotPtr[startSlot + 8] = (stackIntegerValue(3));
	slotPtr[startSlot + 9] = (stackIntegerValue(2));
	slotPtr[startSlot + 10] = (stackIntegerValue(1));
	slotPtr[startSlot + 11] = (stackIntegerValue(0));
	pop(13);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut13 */
EXPORT(sqInt)
primitiveInt32StartingAtPut13(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(14);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(13)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 13) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(12));
	slotPtr[startSlot + 1] = (stackIntegerValue(11));
	slotPtr[startSlot + 2] = (stackIntegerValue(10));
	slotPtr[startSlot + 3] = (stackIntegerValue(9));
	slotPtr[startSlot + 4] = (stackIntegerValue(8));
	slotPtr[startSlot + 5] = (stackIntegerValue(7));
	slotPtr[startSlot + 6] = (stackIntegerValue(6));
	slotPtr[startSlot + 7] = (stackIntegerValue(5));
	slotPtr[startSlot + 8] = (stackIntegerValue(4));
	slotPtr[startSlot + 9] = (stackIntegerValue(3));
	slotPtr[startSlot + 10] = (stackIntegerValue(2));
	slotPtr[startSlot + 11] = (stackIntegerValue(1));
	slotPtr[startSlot + 12] = (stackIntegerValue(0));
	pop(14);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut14 */
EXPORT(sqInt)
primitiveInt32StartingAtPut14(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(15);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(14)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 14) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(13));
	slotPtr[startSlot + 1] = (stackIntegerValue(12));
	slotPtr[startSlot + 2] = (stackIntegerValue(11));
	slotPtr[startSlot + 3] = (stackIntegerValue(10));
	slotPtr[startSlot + 4] = (stackIntegerValue(9));
	slotPtr[startSlot + 5] = (stackIntegerValue(8));
	slotPtr[startSlot + 6] = (stackIntegerValue(7));
	slotPtr[startSlot + 7] = (stackIntegerValue(6));
	slotPtr[startSlot + 8] = (stackIntegerValue(5));
	slotPtr[startSlot + 9] = (stackIntegerValue(4));
	slotPtr[startSlot + 10] = (stackIntegerValue(3));
	slotPtr[startSlot + 11] = (stackIntegerValue(2));
	slotPtr[startSlot + 12] = (stackIntegerValue(1));
	slotPtr[startSlot + 13] = (stackIntegerValue(0));
	pop(15);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut2 */
EXPORT(sqInt)
primitiveInt32StartingAtPut2(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(3);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(2)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 2) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(1));
	slotPtr[startSlot + 1] = (stackIntegerValue(0));
	pop(3);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut3 */
EXPORT(sqInt)
primitiveInt32StartingAtPut3(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(4);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(3)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 3) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(2));
	slotPtr[startSlot + 1] = (stackIntegerValue(1));
	slotPtr[startSlot + 2] = (stackIntegerValue(0));
	pop(4);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut4 */
EXPORT(sqInt)
primitiveInt32StartingAtPut4(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(5);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(4)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 4) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(3));
	slotPtr[startSlot + 1] = (stackIntegerValue(2));
	slotPtr[startSlot + 2] = (stackIntegerValue(1));
	slotPtr[startSlot + 3] = (stackIntegerValue(0));
	pop(5);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut5 */
EXPORT(sqInt)
primitiveInt32StartingAtPut5(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(6);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(5)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 5) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(4));
	slotPtr[startSlot + 1] = (stackIntegerValue(3));
	slotPtr[startSlot + 2] = (stackIntegerValue(2));
	slotPtr[startSlot + 3] = (stackIntegerValue(1));
	slotPtr[startSlot + 4] = (stackIntegerValue(0));
	pop(6);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut6 */
EXPORT(sqInt)
primitiveInt32StartingAtPut6(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(7);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(6)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 6) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(5));
	slotPtr[startSlot + 1] = (stackIntegerValue(4));
	slotPtr[startSlot + 2] = (stackIntegerValue(3));
	slotPtr[startSlot + 3] = (stackIntegerValue(2));
	slotPtr[startSlot + 4] = (stackIntegerValue(1));
	slotPtr[startSlot + 5] = (stackIntegerValue(0));
	pop(7);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut7 */
EXPORT(sqInt)
primitiveInt32StartingAtPut7(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(8);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(7)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 7) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(6));
	slotPtr[startSlot + 1] = (stackIntegerValue(5));
	slotPtr[startSlot + 2] = (stackIntegerValue(4));
	slotPtr[startSlot + 3] = (stackIntegerValue(3));
	slotPtr[startSlot + 4] = (stackIntegerValue(2));
	slotPtr[startSlot + 5] = (stackIntegerValue(1));
	slotPtr[startSlot + 6] = (stackIntegerValue(0));
	pop(8);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut8 */
EXPORT(sqInt)
primitiveInt32StartingAtPut8(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(9);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(8)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 8) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(7));
	slotPtr[startSlot + 1] = (stackIntegerValue(6));
	slotPtr[startSlot + 2] = (stackIntegerValue(5));
	slotPtr[startSlot + 3] = (stackIntegerValue(4));
	slotPtr[startSlot + 4] = (stackIntegerValue(3));
	slotPtr[startSlot + 5] = (stackIntegerValue(2));
	slotPtr[startSlot + 6] = (stackIntegerValue(1));
	slotPtr[startSlot + 7] = (stackIntegerValue(0));
	pop(9);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt32StartingAtPut9 */
EXPORT(sqInt)
primitiveInt32StartingAtPut9(void)
{
    sqInt numSlots;
    sqInt rcvr;
    int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(10);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(9)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 9) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(8));
	slotPtr[startSlot + 1] = (stackIntegerValue(7));
	slotPtr[startSlot + 2] = (stackIntegerValue(6));
	slotPtr[startSlot + 3] = (stackIntegerValue(5));
	slotPtr[startSlot + 4] = (stackIntegerValue(4));
	slotPtr[startSlot + 5] = (stackIntegerValue(3));
	slotPtr[startSlot + 6] = (stackIntegerValue(2));
	slotPtr[startSlot + 7] = (stackIntegerValue(1));
	slotPtr[startSlot + 8] = (stackIntegerValue(0));
	pop(10);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut10 */
EXPORT(sqInt)
primitiveInt64StartingAtPut10(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(11);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(10)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 10) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(9));
	slotPtr[startSlot + 1] = (stackIntegerValue(8));
	slotPtr[startSlot + 2] = (stackIntegerValue(7));
	slotPtr[startSlot + 3] = (stackIntegerValue(6));
	slotPtr[startSlot + 4] = (stackIntegerValue(5));
	slotPtr[startSlot + 5] = (stackIntegerValue(4));
	slotPtr[startSlot + 6] = (stackIntegerValue(3));
	slotPtr[startSlot + 7] = (stackIntegerValue(2));
	slotPtr[startSlot + 8] = (stackIntegerValue(1));
	slotPtr[startSlot + 9] = (stackIntegerValue(0));
	pop(11);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut11 */
EXPORT(sqInt)
primitiveInt64StartingAtPut11(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(12);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(11)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 11) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(10));
	slotPtr[startSlot + 1] = (stackIntegerValue(9));
	slotPtr[startSlot + 2] = (stackIntegerValue(8));
	slotPtr[startSlot + 3] = (stackIntegerValue(7));
	slotPtr[startSlot + 4] = (stackIntegerValue(6));
	slotPtr[startSlot + 5] = (stackIntegerValue(5));
	slotPtr[startSlot + 6] = (stackIntegerValue(4));
	slotPtr[startSlot + 7] = (stackIntegerValue(3));
	slotPtr[startSlot + 8] = (stackIntegerValue(2));
	slotPtr[startSlot + 9] = (stackIntegerValue(1));
	slotPtr[startSlot + 10] = (stackIntegerValue(0));
	pop(12);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut12 */
EXPORT(sqInt)
primitiveInt64StartingAtPut12(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(13);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(12)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 12) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(11));
	slotPtr[startSlot + 1] = (stackIntegerValue(10));
	slotPtr[startSlot + 2] = (stackIntegerValue(9));
	slotPtr[startSlot + 3] = (stackIntegerValue(8));
	slotPtr[startSlot + 4] = (stackIntegerValue(7));
	slotPtr[startSlot + 5] = (stackIntegerValue(6));
	slotPtr[startSlot + 6] = (stackIntegerValue(5));
	slotPtr[startSlot + 7] = (stackIntegerValue(4));
	slotPtr[startSlot + 8] = (stackIntegerValue(3));
	slotPtr[startSlot + 9] = (stackIntegerValue(2));
	slotPtr[startSlot + 10] = (stackIntegerValue(1));
	slotPtr[startSlot + 11] = (stackIntegerValue(0));
	pop(13);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut13 */
EXPORT(sqInt)
primitiveInt64StartingAtPut13(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(14);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(13)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 13) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(12));
	slotPtr[startSlot + 1] = (stackIntegerValue(11));
	slotPtr[startSlot + 2] = (stackIntegerValue(10));
	slotPtr[startSlot + 3] = (stackIntegerValue(9));
	slotPtr[startSlot + 4] = (stackIntegerValue(8));
	slotPtr[startSlot + 5] = (stackIntegerValue(7));
	slotPtr[startSlot + 6] = (stackIntegerValue(6));
	slotPtr[startSlot + 7] = (stackIntegerValue(5));
	slotPtr[startSlot + 8] = (stackIntegerValue(4));
	slotPtr[startSlot + 9] = (stackIntegerValue(3));
	slotPtr[startSlot + 10] = (stackIntegerValue(2));
	slotPtr[startSlot + 11] = (stackIntegerValue(1));
	slotPtr[startSlot + 12] = (stackIntegerValue(0));
	pop(14);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut14 */
EXPORT(sqInt)
primitiveInt64StartingAtPut14(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(15);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(14)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 14) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(13));
	slotPtr[startSlot + 1] = (stackIntegerValue(12));
	slotPtr[startSlot + 2] = (stackIntegerValue(11));
	slotPtr[startSlot + 3] = (stackIntegerValue(10));
	slotPtr[startSlot + 4] = (stackIntegerValue(9));
	slotPtr[startSlot + 5] = (stackIntegerValue(8));
	slotPtr[startSlot + 6] = (stackIntegerValue(7));
	slotPtr[startSlot + 7] = (stackIntegerValue(6));
	slotPtr[startSlot + 8] = (stackIntegerValue(5));
	slotPtr[startSlot + 9] = (stackIntegerValue(4));
	slotPtr[startSlot + 10] = (stackIntegerValue(3));
	slotPtr[startSlot + 11] = (stackIntegerValue(2));
	slotPtr[startSlot + 12] = (stackIntegerValue(1));
	slotPtr[startSlot + 13] = (stackIntegerValue(0));
	pop(15);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut2 */
EXPORT(sqInt)
primitiveInt64StartingAtPut2(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(3);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(2)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 2) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(1));
	slotPtr[startSlot + 1] = (stackIntegerValue(0));
	pop(3);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut3 */
EXPORT(sqInt)
primitiveInt64StartingAtPut3(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(4);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(3)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 3) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(2));
	slotPtr[startSlot + 1] = (stackIntegerValue(1));
	slotPtr[startSlot + 2] = (stackIntegerValue(0));
	pop(4);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut4 */
EXPORT(sqInt)
primitiveInt64StartingAtPut4(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(5);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(4)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 4) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(3));
	slotPtr[startSlot + 1] = (stackIntegerValue(2));
	slotPtr[startSlot + 2] = (stackIntegerValue(1));
	slotPtr[startSlot + 3] = (stackIntegerValue(0));
	pop(5);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut5 */
EXPORT(sqInt)
primitiveInt64StartingAtPut5(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(6);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(5)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 5) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(4));
	slotPtr[startSlot + 1] = (stackIntegerValue(3));
	slotPtr[startSlot + 2] = (stackIntegerValue(2));
	slotPtr[startSlot + 3] = (stackIntegerValue(1));
	slotPtr[startSlot + 4] = (stackIntegerValue(0));
	pop(6);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut6 */
EXPORT(sqInt)
primitiveInt64StartingAtPut6(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(7);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(6)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 6) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(5));
	slotPtr[startSlot + 1] = (stackIntegerValue(4));
	slotPtr[startSlot + 2] = (stackIntegerValue(3));
	slotPtr[startSlot + 3] = (stackIntegerValue(2));
	slotPtr[startSlot + 4] = (stackIntegerValue(1));
	slotPtr[startSlot + 5] = (stackIntegerValue(0));
	pop(7);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut7 */
EXPORT(sqInt)
primitiveInt64StartingAtPut7(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(8);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(7)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 7) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(6));
	slotPtr[startSlot + 1] = (stackIntegerValue(5));
	slotPtr[startSlot + 2] = (stackIntegerValue(4));
	slotPtr[startSlot + 3] = (stackIntegerValue(3));
	slotPtr[startSlot + 4] = (stackIntegerValue(2));
	slotPtr[startSlot + 5] = (stackIntegerValue(1));
	slotPtr[startSlot + 6] = (stackIntegerValue(0));
	pop(8);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut8 */
EXPORT(sqInt)
primitiveInt64StartingAtPut8(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(9);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(8)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 8) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(7));
	slotPtr[startSlot + 1] = (stackIntegerValue(6));
	slotPtr[startSlot + 2] = (stackIntegerValue(5));
	slotPtr[startSlot + 3] = (stackIntegerValue(4));
	slotPtr[startSlot + 4] = (stackIntegerValue(3));
	slotPtr[startSlot + 5] = (stackIntegerValue(2));
	slotPtr[startSlot + 6] = (stackIntegerValue(1));
	slotPtr[startSlot + 7] = (stackIntegerValue(0));
	pop(9);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveInt64StartingAtPut9 */
EXPORT(sqInt)
primitiveInt64StartingAtPut9(void)
{
    sqInt numSlots;
    sqInt rcvr;
    long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(10);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(9)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 9) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(8));
	slotPtr[startSlot + 1] = (stackIntegerValue(7));
	slotPtr[startSlot + 2] = (stackIntegerValue(6));
	slotPtr[startSlot + 3] = (stackIntegerValue(5));
	slotPtr[startSlot + 4] = (stackIntegerValue(4));
	slotPtr[startSlot + 5] = (stackIntegerValue(3));
	slotPtr[startSlot + 6] = (stackIntegerValue(2));
	slotPtr[startSlot + 7] = (stackIntegerValue(1));
	slotPtr[startSlot + 8] = (stackIntegerValue(0));
	pop(10);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut10 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut10(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(11);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(10)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 10) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(9));
	slotPtr[startSlot + 1] = (stackIntegerValue(8));
	slotPtr[startSlot + 2] = (stackIntegerValue(7));
	slotPtr[startSlot + 3] = (stackIntegerValue(6));
	slotPtr[startSlot + 4] = (stackIntegerValue(5));
	slotPtr[startSlot + 5] = (stackIntegerValue(4));
	slotPtr[startSlot + 6] = (stackIntegerValue(3));
	slotPtr[startSlot + 7] = (stackIntegerValue(2));
	slotPtr[startSlot + 8] = (stackIntegerValue(1));
	slotPtr[startSlot + 9] = (stackIntegerValue(0));
	pop(11);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut11 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut11(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(12);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(11)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 11) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(10));
	slotPtr[startSlot + 1] = (stackIntegerValue(9));
	slotPtr[startSlot + 2] = (stackIntegerValue(8));
	slotPtr[startSlot + 3] = (stackIntegerValue(7));
	slotPtr[startSlot + 4] = (stackIntegerValue(6));
	slotPtr[startSlot + 5] = (stackIntegerValue(5));
	slotPtr[startSlot + 6] = (stackIntegerValue(4));
	slotPtr[startSlot + 7] = (stackIntegerValue(3));
	slotPtr[startSlot + 8] = (stackIntegerValue(2));
	slotPtr[startSlot + 9] = (stackIntegerValue(1));
	slotPtr[startSlot + 10] = (stackIntegerValue(0));
	pop(12);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut12 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut12(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(13);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(12)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 12) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(11));
	slotPtr[startSlot + 1] = (stackIntegerValue(10));
	slotPtr[startSlot + 2] = (stackIntegerValue(9));
	slotPtr[startSlot + 3] = (stackIntegerValue(8));
	slotPtr[startSlot + 4] = (stackIntegerValue(7));
	slotPtr[startSlot + 5] = (stackIntegerValue(6));
	slotPtr[startSlot + 6] = (stackIntegerValue(5));
	slotPtr[startSlot + 7] = (stackIntegerValue(4));
	slotPtr[startSlot + 8] = (stackIntegerValue(3));
	slotPtr[startSlot + 9] = (stackIntegerValue(2));
	slotPtr[startSlot + 10] = (stackIntegerValue(1));
	slotPtr[startSlot + 11] = (stackIntegerValue(0));
	pop(13);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut13 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut13(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(14);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(13)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 13) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(12));
	slotPtr[startSlot + 1] = (stackIntegerValue(11));
	slotPtr[startSlot + 2] = (stackIntegerValue(10));
	slotPtr[startSlot + 3] = (stackIntegerValue(9));
	slotPtr[startSlot + 4] = (stackIntegerValue(8));
	slotPtr[startSlot + 5] = (stackIntegerValue(7));
	slotPtr[startSlot + 6] = (stackIntegerValue(6));
	slotPtr[startSlot + 7] = (stackIntegerValue(5));
	slotPtr[startSlot + 8] = (stackIntegerValue(4));
	slotPtr[startSlot + 9] = (stackIntegerValue(3));
	slotPtr[startSlot + 10] = (stackIntegerValue(2));
	slotPtr[startSlot + 11] = (stackIntegerValue(1));
	slotPtr[startSlot + 12] = (stackIntegerValue(0));
	pop(14);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut14 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut14(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(15);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(14)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 14) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(13));
	slotPtr[startSlot + 1] = (stackIntegerValue(12));
	slotPtr[startSlot + 2] = (stackIntegerValue(11));
	slotPtr[startSlot + 3] = (stackIntegerValue(10));
	slotPtr[startSlot + 4] = (stackIntegerValue(9));
	slotPtr[startSlot + 5] = (stackIntegerValue(8));
	slotPtr[startSlot + 6] = (stackIntegerValue(7));
	slotPtr[startSlot + 7] = (stackIntegerValue(6));
	slotPtr[startSlot + 8] = (stackIntegerValue(5));
	slotPtr[startSlot + 9] = (stackIntegerValue(4));
	slotPtr[startSlot + 10] = (stackIntegerValue(3));
	slotPtr[startSlot + 11] = (stackIntegerValue(2));
	slotPtr[startSlot + 12] = (stackIntegerValue(1));
	slotPtr[startSlot + 13] = (stackIntegerValue(0));
	pop(15);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut2 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut2(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(3);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(2)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 2) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(1));
	slotPtr[startSlot + 1] = (stackIntegerValue(0));
	pop(3);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut3 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut3(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(4);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(3)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 3) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(2));
	slotPtr[startSlot + 1] = (stackIntegerValue(1));
	slotPtr[startSlot + 2] = (stackIntegerValue(0));
	pop(4);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut4 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut4(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(5);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(4)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 4) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(3));
	slotPtr[startSlot + 1] = (stackIntegerValue(2));
	slotPtr[startSlot + 2] = (stackIntegerValue(1));
	slotPtr[startSlot + 3] = (stackIntegerValue(0));
	pop(5);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut5 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut5(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(6);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(5)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 5) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(4));
	slotPtr[startSlot + 1] = (stackIntegerValue(3));
	slotPtr[startSlot + 2] = (stackIntegerValue(2));
	slotPtr[startSlot + 3] = (stackIntegerValue(1));
	slotPtr[startSlot + 4] = (stackIntegerValue(0));
	pop(6);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut6 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut6(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(7);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(6)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 6) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(5));
	slotPtr[startSlot + 1] = (stackIntegerValue(4));
	slotPtr[startSlot + 2] = (stackIntegerValue(3));
	slotPtr[startSlot + 3] = (stackIntegerValue(2));
	slotPtr[startSlot + 4] = (stackIntegerValue(1));
	slotPtr[startSlot + 5] = (stackIntegerValue(0));
	pop(7);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut7 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut7(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(8);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(7)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 7) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(6));
	slotPtr[startSlot + 1] = (stackIntegerValue(5));
	slotPtr[startSlot + 2] = (stackIntegerValue(4));
	slotPtr[startSlot + 3] = (stackIntegerValue(3));
	slotPtr[startSlot + 4] = (stackIntegerValue(2));
	slotPtr[startSlot + 5] = (stackIntegerValue(1));
	slotPtr[startSlot + 6] = (stackIntegerValue(0));
	pop(8);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut8 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut8(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(9);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(8)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 8) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(7));
	slotPtr[startSlot + 1] = (stackIntegerValue(6));
	slotPtr[startSlot + 2] = (stackIntegerValue(5));
	slotPtr[startSlot + 3] = (stackIntegerValue(4));
	slotPtr[startSlot + 4] = (stackIntegerValue(3));
	slotPtr[startSlot + 5] = (stackIntegerValue(2));
	slotPtr[startSlot + 6] = (stackIntegerValue(1));
	slotPtr[startSlot + 7] = (stackIntegerValue(0));
	pop(9);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt32StartingAtPut9 */
EXPORT(sqInt)
primitiveUInt32StartingAtPut9(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned int *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(10);
	if (!(isWords(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(9)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 9) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned int *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(8));
	slotPtr[startSlot + 1] = (stackIntegerValue(7));
	slotPtr[startSlot + 2] = (stackIntegerValue(6));
	slotPtr[startSlot + 3] = (stackIntegerValue(5));
	slotPtr[startSlot + 4] = (stackIntegerValue(4));
	slotPtr[startSlot + 5] = (stackIntegerValue(3));
	slotPtr[startSlot + 6] = (stackIntegerValue(2));
	slotPtr[startSlot + 7] = (stackIntegerValue(1));
	slotPtr[startSlot + 8] = (stackIntegerValue(0));
	pop(10);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut10 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut10(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(11);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(10)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 10) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(9));
	slotPtr[startSlot + 1] = (stackIntegerValue(8));
	slotPtr[startSlot + 2] = (stackIntegerValue(7));
	slotPtr[startSlot + 3] = (stackIntegerValue(6));
	slotPtr[startSlot + 4] = (stackIntegerValue(5));
	slotPtr[startSlot + 5] = (stackIntegerValue(4));
	slotPtr[startSlot + 6] = (stackIntegerValue(3));
	slotPtr[startSlot + 7] = (stackIntegerValue(2));
	slotPtr[startSlot + 8] = (stackIntegerValue(1));
	slotPtr[startSlot + 9] = (stackIntegerValue(0));
	pop(11);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut11 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut11(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(12);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(11)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 11) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(10));
	slotPtr[startSlot + 1] = (stackIntegerValue(9));
	slotPtr[startSlot + 2] = (stackIntegerValue(8));
	slotPtr[startSlot + 3] = (stackIntegerValue(7));
	slotPtr[startSlot + 4] = (stackIntegerValue(6));
	slotPtr[startSlot + 5] = (stackIntegerValue(5));
	slotPtr[startSlot + 6] = (stackIntegerValue(4));
	slotPtr[startSlot + 7] = (stackIntegerValue(3));
	slotPtr[startSlot + 8] = (stackIntegerValue(2));
	slotPtr[startSlot + 9] = (stackIntegerValue(1));
	slotPtr[startSlot + 10] = (stackIntegerValue(0));
	pop(12);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut12 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut12(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(13);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(12)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 12) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(11));
	slotPtr[startSlot + 1] = (stackIntegerValue(10));
	slotPtr[startSlot + 2] = (stackIntegerValue(9));
	slotPtr[startSlot + 3] = (stackIntegerValue(8));
	slotPtr[startSlot + 4] = (stackIntegerValue(7));
	slotPtr[startSlot + 5] = (stackIntegerValue(6));
	slotPtr[startSlot + 6] = (stackIntegerValue(5));
	slotPtr[startSlot + 7] = (stackIntegerValue(4));
	slotPtr[startSlot + 8] = (stackIntegerValue(3));
	slotPtr[startSlot + 9] = (stackIntegerValue(2));
	slotPtr[startSlot + 10] = (stackIntegerValue(1));
	slotPtr[startSlot + 11] = (stackIntegerValue(0));
	pop(13);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut13 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut13(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(14);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(13)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 13) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(12));
	slotPtr[startSlot + 1] = (stackIntegerValue(11));
	slotPtr[startSlot + 2] = (stackIntegerValue(10));
	slotPtr[startSlot + 3] = (stackIntegerValue(9));
	slotPtr[startSlot + 4] = (stackIntegerValue(8));
	slotPtr[startSlot + 5] = (stackIntegerValue(7));
	slotPtr[startSlot + 6] = (stackIntegerValue(6));
	slotPtr[startSlot + 7] = (stackIntegerValue(5));
	slotPtr[startSlot + 8] = (stackIntegerValue(4));
	slotPtr[startSlot + 9] = (stackIntegerValue(3));
	slotPtr[startSlot + 10] = (stackIntegerValue(2));
	slotPtr[startSlot + 11] = (stackIntegerValue(1));
	slotPtr[startSlot + 12] = (stackIntegerValue(0));
	pop(14);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut14 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut14(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(15);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(14)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 14) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(13));
	slotPtr[startSlot + 1] = (stackIntegerValue(12));
	slotPtr[startSlot + 2] = (stackIntegerValue(11));
	slotPtr[startSlot + 3] = (stackIntegerValue(10));
	slotPtr[startSlot + 4] = (stackIntegerValue(9));
	slotPtr[startSlot + 5] = (stackIntegerValue(8));
	slotPtr[startSlot + 6] = (stackIntegerValue(7));
	slotPtr[startSlot + 7] = (stackIntegerValue(6));
	slotPtr[startSlot + 8] = (stackIntegerValue(5));
	slotPtr[startSlot + 9] = (stackIntegerValue(4));
	slotPtr[startSlot + 10] = (stackIntegerValue(3));
	slotPtr[startSlot + 11] = (stackIntegerValue(2));
	slotPtr[startSlot + 12] = (stackIntegerValue(1));
	slotPtr[startSlot + 13] = (stackIntegerValue(0));
	pop(15);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut2 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut2(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(3);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(2)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 2) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(1));
	slotPtr[startSlot + 1] = (stackIntegerValue(0));
	pop(3);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut3 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut3(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(4);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(3)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 3) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(2));
	slotPtr[startSlot + 1] = (stackIntegerValue(1));
	slotPtr[startSlot + 2] = (stackIntegerValue(0));
	pop(4);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut4 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut4(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(5);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(4)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 4) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(3));
	slotPtr[startSlot + 1] = (stackIntegerValue(2));
	slotPtr[startSlot + 2] = (stackIntegerValue(1));
	slotPtr[startSlot + 3] = (stackIntegerValue(0));
	pop(5);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut5 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut5(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(6);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(5)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 5) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(4));
	slotPtr[startSlot + 1] = (stackIntegerValue(3));
	slotPtr[startSlot + 2] = (stackIntegerValue(2));
	slotPtr[startSlot + 3] = (stackIntegerValue(1));
	slotPtr[startSlot + 4] = (stackIntegerValue(0));
	pop(6);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut6 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut6(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(7);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(6)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 6) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(5));
	slotPtr[startSlot + 1] = (stackIntegerValue(4));
	slotPtr[startSlot + 2] = (stackIntegerValue(3));
	slotPtr[startSlot + 3] = (stackIntegerValue(2));
	slotPtr[startSlot + 4] = (stackIntegerValue(1));
	slotPtr[startSlot + 5] = (stackIntegerValue(0));
	pop(7);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut7 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut7(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(8);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(7)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 7) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(6));
	slotPtr[startSlot + 1] = (stackIntegerValue(5));
	slotPtr[startSlot + 2] = (stackIntegerValue(4));
	slotPtr[startSlot + 3] = (stackIntegerValue(3));
	slotPtr[startSlot + 4] = (stackIntegerValue(2));
	slotPtr[startSlot + 5] = (stackIntegerValue(1));
	slotPtr[startSlot + 6] = (stackIntegerValue(0));
	pop(8);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut8 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut8(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(9);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(8)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 8) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(7));
	slotPtr[startSlot + 1] = (stackIntegerValue(6));
	slotPtr[startSlot + 2] = (stackIntegerValue(5));
	slotPtr[startSlot + 3] = (stackIntegerValue(4));
	slotPtr[startSlot + 4] = (stackIntegerValue(3));
	slotPtr[startSlot + 5] = (stackIntegerValue(2));
	slotPtr[startSlot + 6] = (stackIntegerValue(1));
	slotPtr[startSlot + 7] = (stackIntegerValue(0));
	pop(9);
	return 0;
}

	/* ArrayBulkPlugin>>#primitiveUInt64StartingAtPut9 */
EXPORT(sqInt)
primitiveUInt64StartingAtPut9(void)
{
    sqInt numSlots;
    sqInt rcvr;
    unsigned long long *slotPtr;
    sqInt startSlot;

	rcvr = stackValue(10);
	if (!(isLong64s(rcvr))) {
		return primitiveFailFor(PrimErrBadReceiver);
	}
	startSlot = (stackIntegerValue(9)) - 1;
	numSlots = slotSizeOf(rcvr);
	if ((failed())
	 || ((startSlot < 0)
	 || ((startSlot + 9) > numSlots))) {
		return primitiveFailFor(PrimErrBadIndex);
	}
	slotPtr = ((unsigned long long *) (firstIndexableField(rcvr)));
	slotPtr[startSlot] = (stackIntegerValue(8));
	slotPtr[startSlot + 1] = (stackIntegerValue(7));
	slotPtr[startSlot + 2] = (stackIntegerValue(6));
	slotPtr[startSlot + 3] = (stackIntegerValue(5));
	slotPtr[startSlot + 4] = (stackIntegerValue(4));
	slotPtr[startSlot + 5] = (stackIntegerValue(3));
	slotPtr[startSlot + 6] = (stackIntegerValue(2));
	slotPtr[startSlot + 7] = (stackIntegerValue(1));
	slotPtr[startSlot + 8] = (stackIntegerValue(0));
	pop(10);
	return 0;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine *anInterpreter)
{
    sqInt ok;


	/* This may seem tautological, but in a real plugin it checks that the VM provides
	   the version the plugin was compiled against which is the version the plugin expects. */
	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {
		
#if !defined(SQUEAK_BUILTIN_PLUGIN)
		failed = interpreterProxy->failed;
		firstIndexableField = interpreterProxy->firstIndexableField;
#if VM_PROXY_MAJOR > 1 || (VM_PROXY_MAJOR == 1 && VM_PROXY_MINOR >= 17)
		isLong64s = interpreterProxy->isLong64s;
#else
#if !defined(isLong64s)
		isLong64s = 0;
#endif
#endif
		isWords = interpreterProxy->isWords;
		pop = interpreterProxy->pop;
		primitiveFailFor = interpreterProxy->primitiveFailFor;
		slotSizeOf = interpreterProxy->slotSizeOf;
		stackFloatValue = interpreterProxy->stackFloatValue;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackValue = interpreterProxy->stackValue;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "ArrayBulkPlugin";
void* ArrayBulkPlugin_exports[][3] = {
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "primitiveFloat32StartingAtPut10\000\001\000", (void*)primitiveFloat32StartingAtPut10},
	{(void*)_m, "primitiveFloat32StartingAtPut11\000\001\000", (void*)primitiveFloat32StartingAtPut11},
	{(void*)_m, "primitiveFloat32StartingAtPut12\000\001\000", (void*)primitiveFloat32StartingAtPut12},
	{(void*)_m, "primitiveFloat32StartingAtPut13\000\001\000", (void*)primitiveFloat32StartingAtPut13},
	{(void*)_m, "primitiveFloat32StartingAtPut14\000\001\000", (void*)primitiveFloat32StartingAtPut14},
	{(void*)_m, "primitiveFloat32StartingAtPut2\000\001\000", (void*)primitiveFloat32StartingAtPut2},
	{(void*)_m, "primitiveFloat32StartingAtPut3\000\001\000", (void*)primitiveFloat32StartingAtPut3},
	{(void*)_m, "primitiveFloat32StartingAtPut4\000\001\000", (void*)primitiveFloat32StartingAtPut4},
	{(void*)_m, "primitiveFloat32StartingAtPut5\000\001\000", (void*)primitiveFloat32StartingAtPut5},
	{(void*)_m, "primitiveFloat32StartingAtPut6\000\001\000", (void*)primitiveFloat32StartingAtPut6},
	{(void*)_m, "primitiveFloat32StartingAtPut7\000\001\000", (void*)primitiveFloat32StartingAtPut7},
	{(void*)_m, "primitiveFloat32StartingAtPut8\000\001\000", (void*)primitiveFloat32StartingAtPut8},
	{(void*)_m, "primitiveFloat32StartingAtPut9\000\001\000", (void*)primitiveFloat32StartingAtPut9},
	{(void*)_m, "primitiveFloat64StartingAtPut10\000\001\000", (void*)primitiveFloat64StartingAtPut10},
	{(void*)_m, "primitiveFloat64StartingAtPut11\000\001\000", (void*)primitiveFloat64StartingAtPut11},
	{(void*)_m, "primitiveFloat64StartingAtPut12\000\001\000", (void*)primitiveFloat64StartingAtPut12},
	{(void*)_m, "primitiveFloat64StartingAtPut13\000\001\000", (void*)primitiveFloat64StartingAtPut13},
	{(void*)_m, "primitiveFloat64StartingAtPut14\000\001\000", (void*)primitiveFloat64StartingAtPut14},
	{(void*)_m, "primitiveFloat64StartingAtPut2\000\001\000", (void*)primitiveFloat64StartingAtPut2},
	{(void*)_m, "primitiveFloat64StartingAtPut3\000\001\000", (void*)primitiveFloat64StartingAtPut3},
	{(void*)_m, "primitiveFloat64StartingAtPut4\000\001\000", (void*)primitiveFloat64StartingAtPut4},
	{(void*)_m, "primitiveFloat64StartingAtPut5\000\001\000", (void*)primitiveFloat64StartingAtPut5},
	{(void*)_m, "primitiveFloat64StartingAtPut6\000\001\000", (void*)primitiveFloat64StartingAtPut6},
	{(void*)_m, "primitiveFloat64StartingAtPut7\000\001\000", (void*)primitiveFloat64StartingAtPut7},
	{(void*)_m, "primitiveFloat64StartingAtPut8\000\001\000", (void*)primitiveFloat64StartingAtPut8},
	{(void*)_m, "primitiveFloat64StartingAtPut9\000\001\000", (void*)primitiveFloat64StartingAtPut9},
	{(void*)_m, "primitiveInt32StartingAtPut10\000\001\000", (void*)primitiveInt32StartingAtPut10},
	{(void*)_m, "primitiveInt32StartingAtPut11\000\001\000", (void*)primitiveInt32StartingAtPut11},
	{(void*)_m, "primitiveInt32StartingAtPut12\000\001\000", (void*)primitiveInt32StartingAtPut12},
	{(void*)_m, "primitiveInt32StartingAtPut13\000\001\000", (void*)primitiveInt32StartingAtPut13},
	{(void*)_m, "primitiveInt32StartingAtPut14\000\001\000", (void*)primitiveInt32StartingAtPut14},
	{(void*)_m, "primitiveInt32StartingAtPut2\000\001\000", (void*)primitiveInt32StartingAtPut2},
	{(void*)_m, "primitiveInt32StartingAtPut3\000\001\000", (void*)primitiveInt32StartingAtPut3},
	{(void*)_m, "primitiveInt32StartingAtPut4\000\001\000", (void*)primitiveInt32StartingAtPut4},
	{(void*)_m, "primitiveInt32StartingAtPut5\000\001\000", (void*)primitiveInt32StartingAtPut5},
	{(void*)_m, "primitiveInt32StartingAtPut6\000\001\000", (void*)primitiveInt32StartingAtPut6},
	{(void*)_m, "primitiveInt32StartingAtPut7\000\001\000", (void*)primitiveInt32StartingAtPut7},
	{(void*)_m, "primitiveInt32StartingAtPut8\000\001\000", (void*)primitiveInt32StartingAtPut8},
	{(void*)_m, "primitiveInt32StartingAtPut9\000\001\000", (void*)primitiveInt32StartingAtPut9},
	{(void*)_m, "primitiveInt64StartingAtPut10\000\001\000", (void*)primitiveInt64StartingAtPut10},
	{(void*)_m, "primitiveInt64StartingAtPut11\000\001\000", (void*)primitiveInt64StartingAtPut11},
	{(void*)_m, "primitiveInt64StartingAtPut12\000\001\000", (void*)primitiveInt64StartingAtPut12},
	{(void*)_m, "primitiveInt64StartingAtPut13\000\001\000", (void*)primitiveInt64StartingAtPut13},
	{(void*)_m, "primitiveInt64StartingAtPut14\000\001\000", (void*)primitiveInt64StartingAtPut14},
	{(void*)_m, "primitiveInt64StartingAtPut2\000\001\000", (void*)primitiveInt64StartingAtPut2},
	{(void*)_m, "primitiveInt64StartingAtPut3\000\001\000", (void*)primitiveInt64StartingAtPut3},
	{(void*)_m, "primitiveInt64StartingAtPut4\000\001\000", (void*)primitiveInt64StartingAtPut4},
	{(void*)_m, "primitiveInt64StartingAtPut5\000\001\000", (void*)primitiveInt64StartingAtPut5},
	{(void*)_m, "primitiveInt64StartingAtPut6\000\001\000", (void*)primitiveInt64StartingAtPut6},
	{(void*)_m, "primitiveInt64StartingAtPut7\000\001\000", (void*)primitiveInt64StartingAtPut7},
	{(void*)_m, "primitiveInt64StartingAtPut8\000\001\000", (void*)primitiveInt64StartingAtPut8},
	{(void*)_m, "primitiveInt64StartingAtPut9\000\001\000", (void*)primitiveInt64StartingAtPut9},
	{(void*)_m, "primitiveUInt32StartingAtPut10\000\001\000", (void*)primitiveUInt32StartingAtPut10},
	{(void*)_m, "primitiveUInt32StartingAtPut11\000\001\000", (void*)primitiveUInt32StartingAtPut11},
	{(void*)_m, "primitiveUInt32StartingAtPut12\000\001\000", (void*)primitiveUInt32StartingAtPut12},
	{(void*)_m, "primitiveUInt32StartingAtPut13\000\001\000", (void*)primitiveUInt32StartingAtPut13},
	{(void*)_m, "primitiveUInt32StartingAtPut14\000\001\000", (void*)primitiveUInt32StartingAtPut14},
	{(void*)_m, "primitiveUInt32StartingAtPut2\000\001\000", (void*)primitiveUInt32StartingAtPut2},
	{(void*)_m, "primitiveUInt32StartingAtPut3\000\001\000", (void*)primitiveUInt32StartingAtPut3},
	{(void*)_m, "primitiveUInt32StartingAtPut4\000\001\000", (void*)primitiveUInt32StartingAtPut4},
	{(void*)_m, "primitiveUInt32StartingAtPut5\000\001\000", (void*)primitiveUInt32StartingAtPut5},
	{(void*)_m, "primitiveUInt32StartingAtPut6\000\001\000", (void*)primitiveUInt32StartingAtPut6},
	{(void*)_m, "primitiveUInt32StartingAtPut7\000\001\000", (void*)primitiveUInt32StartingAtPut7},
	{(void*)_m, "primitiveUInt32StartingAtPut8\000\001\000", (void*)primitiveUInt32StartingAtPut8},
	{(void*)_m, "primitiveUInt32StartingAtPut9\000\001\000", (void*)primitiveUInt32StartingAtPut9},
	{(void*)_m, "primitiveUInt64StartingAtPut10\000\001\000", (void*)primitiveUInt64StartingAtPut10},
	{(void*)_m, "primitiveUInt64StartingAtPut11\000\001\000", (void*)primitiveUInt64StartingAtPut11},
	{(void*)_m, "primitiveUInt64StartingAtPut12\000\001\000", (void*)primitiveUInt64StartingAtPut12},
	{(void*)_m, "primitiveUInt64StartingAtPut13\000\001\000", (void*)primitiveUInt64StartingAtPut13},
	{(void*)_m, "primitiveUInt64StartingAtPut14\000\001\000", (void*)primitiveUInt64StartingAtPut14},
	{(void*)_m, "primitiveUInt64StartingAtPut2\000\001\000", (void*)primitiveUInt64StartingAtPut2},
	{(void*)_m, "primitiveUInt64StartingAtPut3\000\001\000", (void*)primitiveUInt64StartingAtPut3},
	{(void*)_m, "primitiveUInt64StartingAtPut4\000\001\000", (void*)primitiveUInt64StartingAtPut4},
	{(void*)_m, "primitiveUInt64StartingAtPut5\000\001\000", (void*)primitiveUInt64StartingAtPut5},
	{(void*)_m, "primitiveUInt64StartingAtPut6\000\001\000", (void*)primitiveUInt64StartingAtPut6},
	{(void*)_m, "primitiveUInt64StartingAtPut7\000\001\000", (void*)primitiveUInt64StartingAtPut7},
	{(void*)_m, "primitiveUInt64StartingAtPut8\000\001\000", (void*)primitiveUInt64StartingAtPut8},
	{(void*)_m, "primitiveUInt64StartingAtPut9\000\001\000", (void*)primitiveUInt64StartingAtPut9},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else // ifdef SQ_BUILTIN_PLUGIN

#if SPURVM
EXPORT(signed short) primitiveFloat32StartingAtPut10Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut11Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut12Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut13Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut14Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut2Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut3Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut4Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut5Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut6Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut7Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut8Metadata = 0x100;
EXPORT(signed short) primitiveFloat32StartingAtPut9Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut10Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut11Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut12Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut13Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut14Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut2Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut3Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut4Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut5Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut6Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut7Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut8Metadata = 0x100;
EXPORT(signed short) primitiveFloat64StartingAtPut9Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut10Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut11Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut12Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut13Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut14Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut2Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut3Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut4Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut5Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut6Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut7Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut8Metadata = 0x100;
EXPORT(signed short) primitiveInt32StartingAtPut9Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut10Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut11Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut12Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut13Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut14Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut2Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut3Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut4Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut5Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut6Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut7Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut8Metadata = 0x100;
EXPORT(signed short) primitiveInt64StartingAtPut9Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut10Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut11Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut12Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut13Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut14Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut2Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut3Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut4Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut5Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut6Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut7Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut8Metadata = 0x100;
EXPORT(signed short) primitiveUInt32StartingAtPut9Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut10Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut11Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut12Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut13Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut14Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut2Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut3Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut4Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut5Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut6Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut7Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut8Metadata = 0x100;
EXPORT(signed short) primitiveUInt64StartingAtPut9Metadata = 0x100;
#endif // SPURVM

#endif // ifdef SQ_BUILTIN_PLUGIN
