Class {
	#name : #'GL1_5',
	#superclass : #'GL1_4',
	#category : #'OpenGL-API-GL',
	#commentStamp : ''
}

{
	#category : #accessing,
	#timestamp : ''
}
GL1_5 class >> majorVersion [

	^ 1
]

{
	#category : #accessing,
	#timestamp : ''
}
GL1_5 class >> minorVersion [

	^ 5
]

{
	#category : #accessing,
	#timestamp : ''
}
GL1_5 class >> versionNumber [

	^ 15
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> ARRAY_BUFFER [

	<generated>
	^ GL_ARRAY_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> BUFFER_ACCESS [

	<generated>
	^ GL_BUFFER_ACCESS
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> BUFFER_MAPPED [

	<generated>
	^ GL_BUFFER_MAPPED
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> BUFFER_MAP_POINTER [

	<generated>
	^ GL_BUFFER_MAP_POINTER
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> BUFFER_SIZE [

	<generated>
	^ GL_BUFFER_SIZE
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> BUFFER_USAGE [

	<generated>
	^ GL_BUFFER_USAGE
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> COLOR_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_COLOR_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> CURRENT_FOG_COORD [

	<generated>
	^ GL_CURRENT_FOG_COORD
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> CURRENT_QUERY [

	<generated>
	^ GL_CURRENT_QUERY
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> DYNAMIC_COPY [

	<generated>
	^ GL_DYNAMIC_COPY
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> DYNAMIC_DRAW [

	<generated>
	^ GL_DYNAMIC_DRAW
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> DYNAMIC_READ [

	<generated>
	^ GL_DYNAMIC_READ
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> EDGE_FLAG_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_EDGE_FLAG_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> ELEMENT_ARRAY_BUFFER [

	<generated>
	^ GL_ELEMENT_ARRAY_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> ELEMENT_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_ELEMENT_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD [

	<generated>
	^ GL_FOG_COORD
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORDINATE_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD_ARRAY [

	<generated>
	^ GL_FOG_COORD_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_FOG_COORD_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD_ARRAY_POINTER [

	<generated>
	^ GL_FOG_COORD_ARRAY_POINTER
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD_ARRAY_STRIDE [

	<generated>
	^ GL_FOG_COORD_ARRAY_STRIDE
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD_ARRAY_TYPE [

	<generated>
	^ GL_FOG_COORD_ARRAY_TYPE
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> FOG_COORD_SRC [

	<generated>
	^ GL_FOG_COORD_SRC
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> INDEX_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_INDEX_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> NORMAL_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_NORMAL_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> QUERY_COUNTER_BITS [

	<generated>
	^ GL_QUERY_COUNTER_BITS
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> QUERY_RESULT [

	<generated>
	^ GL_QUERY_RESULT
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> QUERY_RESULT_AVAILABLE [

	<generated>
	^ GL_QUERY_RESULT_AVAILABLE
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> READ_ONLY [

	<generated>
	^ GL_READ_ONLY
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> READ_WRITE [

	<generated>
	^ GL_READ_WRITE
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SAMPLES_PASSED [

	<generated>
	^ GL_SAMPLES_PASSED
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SECONDARY_COLOR_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SRC0_ALPHA [

	<generated>
	^ GL_SRC0_ALPHA
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SRC0_RGB [

	<generated>
	^ GL_SRC0_RGB
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SRC1_ALPHA [

	<generated>
	^ GL_SRC1_ALPHA
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SRC1_RGB [

	<generated>
	^ GL_SRC1_RGB
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SRC2_ALPHA [

	<generated>
	^ GL_SRC2_ALPHA
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> SRC2_RGB [

	<generated>
	^ GL_SRC2_RGB
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> STATIC_COPY [

	<generated>
	^ GL_STATIC_COPY
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> STATIC_DRAW [

	<generated>
	^ GL_STATIC_DRAW
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> STATIC_READ [

	<generated>
	^ GL_STATIC_READ
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> STREAM_COPY [

	<generated>
	^ GL_STREAM_COPY
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> STREAM_DRAW [

	<generated>
	^ GL_STREAM_DRAW
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> STREAM_READ [

	<generated>
	^ GL_STREAM_READ
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> TEXTURE_COORD_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> VERTEX_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_VERTEX_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> VERTEX_ATTRIB_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> WEIGHT_ARRAY_BUFFER_BINDING [

	<generated>
	^ GL_WEIGHT_ARRAY_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : ''
}
GL1_5 >> WRITE_ONLY [

	<generated>
	^ GL_WRITE_ONLY
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> beginQuery: target with: id [

	<generated>
	<apicall: void 'glBeginQuery' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> bindBuffer: target with: buffer [

	<generated>
	<apicall: void 'glBindBuffer' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> bufferData: target with: size with: data with: usage [

	<generated>
	<apicall: void 'glBufferData' (GLenum GLsizeiptr void* GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> bufferSubData: target with: offset with: size with: data [

	<generated>
	<apicall: void 'glBufferSubData' (GLenum GLintptr GLsizeiptr void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> deleteBuffers: n with: buffers [

	<generated>
	<apicall: void 'glDeleteBuffers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> deleteQueries: n with: ids [

	<generated>
	<apicall: void 'glDeleteQueries' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> endQuery: target [

	<generated>
	<apicall: void 'glEndQuery' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> genBuffers: n with: buffers [

	<generated>
	<apicall: void 'glGenBuffers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> genQueries: n with: ids [

	<generated>
	<apicall: void 'glGenQueries' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> getBufferParameteriv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetBufferParameteriv' (GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> getBufferPointerv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetBufferPointerv' (GLenum GLenum void**)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> getBufferSubData: target with: offset with: size with: data [

	<generated>
	<apicall: void 'glGetBufferSubData' (GLenum GLintptr GLsizeiptr void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> getQueryObjectiv: id with: pname with: params [

	<generated>
	<apicall: void 'glGetQueryObjectiv' (GLuint GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> getQueryObjectuiv: id with: pname with: params [

	<generated>
	<apicall: void 'glGetQueryObjectuiv' (GLuint GLenum GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> getQueryiv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetQueryiv' (GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> isBuffer: buffer [

	<generated>
	<apicall: GLboolean 'glIsBuffer' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> isQuery: id [

	<generated>
	<apicall: GLboolean 'glIsQuery' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> mapBuffer: target with: access [

	<generated>
	<apicall: void* 'glMapBuffer' (GLenum GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : ''
}
GL1_5 >> unmapBuffer: target [

	<generated>
	<apicall: GLboolean 'glUnmapBuffer' (GLenum)>
	^ self externalCallFailed
]
