Class {
	#name : #'GL3_0',
	#superclass : #'GL2_1',
	#category : #'OpenGL-API-GL',
	#commentStamp : ''
}

{
	#category : #accessing,
	#timestamp : 'stlu 11/13/2020 18:20'
}
GL3_0 class >> majorVersion [

	^ 3
]

{
	#category : #accessing,
	#timestamp : 'stlu 11/13/2020 18:20'
}
GL3_0 class >> minorVersion [

	^ 0
]

{
	#category : #accessing,
	#timestamp : 'stlu 11/2/2020 14:51'
}
GL3_0 class >> versionNumber [

	^ 30
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> ALPHA_INTEGER [

	<generated>
	^ GL_ALPHA_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> BGRA_INTEGER [

	<generated>
	^ GL_BGRA_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> BGR_INTEGER [

	<generated>
	^ GL_BGR_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> BLUE_INTEGER [

	<generated>
	^ GL_BLUE_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> BUFFER_ACCESS_FLAGS [

	<generated>
	^ GL_BUFFER_ACCESS_FLAGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> BUFFER_MAP_LENGTH [

	<generated>
	^ GL_BUFFER_MAP_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> BUFFER_MAP_OFFSET [

	<generated>
	^ GL_BUFFER_MAP_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLAMP_FRAGMENT_COLOR [

	<generated>
	^ GL_CLAMP_FRAGMENT_COLOR
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLAMP_READ_COLOR [

	<generated>
	^ GL_CLAMP_READ_COLOR
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLAMP_VERTEX_COLOR [

	<generated>
	^ GL_CLAMP_VERTEX_COLOR
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE0 [

	<generated>
	^ GL_CLIP_DISTANCE0
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE1 [

	<generated>
	^ GL_CLIP_DISTANCE1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE2 [

	<generated>
	^ GL_CLIP_DISTANCE2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE3 [

	<generated>
	^ GL_CLIP_DISTANCE3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE4 [

	<generated>
	^ GL_CLIP_DISTANCE4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE5 [

	<generated>
	^ GL_CLIP_DISTANCE5
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE6 [

	<generated>
	^ GL_CLIP_DISTANCE6
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CLIP_DISTANCE7 [

	<generated>
	^ GL_CLIP_DISTANCE7
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT0 [

	<generated>
	^ GL_COLOR_ATTACHMENT0
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT1 [

	<generated>
	^ GL_COLOR_ATTACHMENT1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT10 [

	<generated>
	^ GL_COLOR_ATTACHMENT10
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT11 [

	<generated>
	^ GL_COLOR_ATTACHMENT11
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT12 [

	<generated>
	^ GL_COLOR_ATTACHMENT12
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT13 [

	<generated>
	^ GL_COLOR_ATTACHMENT13
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT14 [

	<generated>
	^ GL_COLOR_ATTACHMENT14
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT15 [

	<generated>
	^ GL_COLOR_ATTACHMENT15
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT16 [

	<generated>
	^ GL_COLOR_ATTACHMENT16
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT17 [

	<generated>
	^ GL_COLOR_ATTACHMENT17
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT18 [

	<generated>
	^ GL_COLOR_ATTACHMENT18
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT19 [

	<generated>
	^ GL_COLOR_ATTACHMENT19
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT2 [

	<generated>
	^ GL_COLOR_ATTACHMENT2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT20 [

	<generated>
	^ GL_COLOR_ATTACHMENT20
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT21 [

	<generated>
	^ GL_COLOR_ATTACHMENT21
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT22 [

	<generated>
	^ GL_COLOR_ATTACHMENT22
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT23 [

	<generated>
	^ GL_COLOR_ATTACHMENT23
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT24 [

	<generated>
	^ GL_COLOR_ATTACHMENT24
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT25 [

	<generated>
	^ GL_COLOR_ATTACHMENT25
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT26 [

	<generated>
	^ GL_COLOR_ATTACHMENT26
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT27 [

	<generated>
	^ GL_COLOR_ATTACHMENT27
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT28 [

	<generated>
	^ GL_COLOR_ATTACHMENT28
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT29 [

	<generated>
	^ GL_COLOR_ATTACHMENT29
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT3 [

	<generated>
	^ GL_COLOR_ATTACHMENT3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT30 [

	<generated>
	^ GL_COLOR_ATTACHMENT30
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT31 [

	<generated>
	^ GL_COLOR_ATTACHMENT31
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT4 [

	<generated>
	^ GL_COLOR_ATTACHMENT4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT5 [

	<generated>
	^ GL_COLOR_ATTACHMENT5
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT6 [

	<generated>
	^ GL_COLOR_ATTACHMENT6
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT7 [

	<generated>
	^ GL_COLOR_ATTACHMENT7
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT8 [

	<generated>
	^ GL_COLOR_ATTACHMENT8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COLOR_ATTACHMENT9 [

	<generated>
	^ GL_COLOR_ATTACHMENT9
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPARE_REF_TO_TEXTURE [

	<generated>
	^ GL_COMPARE_REF_TO_TEXTURE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPRESSED_RED [

	<generated>
	^ GL_COMPRESSED_RED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPRESSED_RED_RGTC1 [

	<generated>
	^ GL_COMPRESSED_RED_RGTC1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPRESSED_RG [

	<generated>
	^ GL_COMPRESSED_RG
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPRESSED_RG_RGTC2 [

	<generated>
	^ GL_COMPRESSED_RG_RGTC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPRESSED_SIGNED_RED_RGTC1 [

	<generated>
	^ GL_COMPRESSED_SIGNED_RED_RGTC1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> COMPRESSED_SIGNED_RG_RGTC2 [

	<generated>
	^ GL_COMPRESSED_SIGNED_RG_RGTC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CONTEXT_FLAGS [

	<generated>
	^ GL_CONTEXT_FLAGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT [

	<generated>
	^ GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DEPTH24_STENCIL8 [

	<generated>
	^ GL_DEPTH24_STENCIL8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DEPTH32F_STENCIL8 [

	<generated>
	^ GL_DEPTH32F_STENCIL8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DEPTH_ATTACHMENT [

	<generated>
	^ GL_DEPTH_ATTACHMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DEPTH_COMPONENT32F [

	<generated>
	^ GL_DEPTH_COMPONENT32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DEPTH_STENCIL [

	<generated>
	^ GL_DEPTH_STENCIL
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DEPTH_STENCIL_ATTACHMENT [

	<generated>
	^ GL_DEPTH_STENCIL_ATTACHMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DRAW_FRAMEBUFFER [

	<generated>
	^ GL_DRAW_FRAMEBUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> DRAW_FRAMEBUFFER_BINDING [

	<generated>
	^ GL_DRAW_FRAMEBUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FIXED_ONLY [

	<generated>
	^ GL_FIXED_ONLY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FLOAT_32_UNSIGNED_INT_24_8_REV [

	<generated>
	^ GL_FLOAT_32_UNSIGNED_INT_24_8_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER [

	<generated>
	^ GL_FRAMEBUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_BLUE_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_GREEN_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_OBJECT_NAME [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_RED_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_BINDING [

	<generated>
	^ GL_FRAMEBUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_COMPLETE [

	<generated>
	^ GL_FRAMEBUFFER_COMPLETE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_DEFAULT [

	<generated>
	^ GL_FRAMEBUFFER_DEFAULT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_INCOMPLETE_ATTACHMENT [

	<generated>
	^ GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER [

	<generated>
	^ GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT [

	<generated>
	^ GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_INCOMPLETE_MULTISAMPLE [

	<generated>
	^ GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_INCOMPLETE_READ_BUFFER [

	<generated>
	^ GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_SRGB [

	<generated>
	^ GL_FRAMEBUFFER_SRGB
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_UNDEFINED [

	<generated>
	^ GL_FRAMEBUFFER_UNDEFINED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> FRAMEBUFFER_UNSUPPORTED [

	<generated>
	^ GL_FRAMEBUFFER_UNSUPPORTED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> GREEN_INTEGER [

	<generated>
	^ GL_GREEN_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> HALF_FLOAT [

	<generated>
	^ GL_HALF_FLOAT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INDEX [

	<generated>
	^ GL_INDEX
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INTERLEAVED_ATTRIBS [

	<generated>
	^ GL_INTERLEAVED_ATTRIBS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INT_SAMPLER_1D [

	<generated>
	^ GL_INT_SAMPLER_1D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INT_SAMPLER_1D_ARRAY [

	<generated>
	^ GL_INT_SAMPLER_1D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INT_SAMPLER_2D [

	<generated>
	^ GL_INT_SAMPLER_2D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INT_SAMPLER_2D_ARRAY [

	<generated>
	^ GL_INT_SAMPLER_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INT_SAMPLER_3D [

	<generated>
	^ GL_INT_SAMPLER_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INT_SAMPLER_CUBE [

	<generated>
	^ GL_INT_SAMPLER_CUBE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> INVALID_FRAMEBUFFER_OPERATION [

	<generated>
	^ GL_INVALID_FRAMEBUFFER_OPERATION
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAJOR_VERSION [

	<generated>
	^ GL_MAJOR_VERSION
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAP_FLUSH_EXPLICIT_BIT [

	<generated>
	^ GL_MAP_FLUSH_EXPLICIT_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAP_INVALIDATE_BUFFER_BIT [

	<generated>
	^ GL_MAP_INVALIDATE_BUFFER_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAP_INVALIDATE_RANGE_BIT [

	<generated>
	^ GL_MAP_INVALIDATE_RANGE_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAP_READ_BIT [

	<generated>
	^ GL_MAP_READ_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAP_UNSYNCHRONIZED_BIT [

	<generated>
	^ GL_MAP_UNSYNCHRONIZED_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAP_WRITE_BIT [

	<generated>
	^ GL_MAP_WRITE_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_ARRAY_TEXTURE_LAYERS [

	<generated>
	^ GL_MAX_ARRAY_TEXTURE_LAYERS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_CLIP_DISTANCES [

	<generated>
	^ GL_MAX_CLIP_DISTANCES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_COLOR_ATTACHMENTS [

	<generated>
	^ GL_MAX_COLOR_ATTACHMENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_PROGRAM_TEXEL_OFFSET [

	<generated>
	^ GL_MAX_PROGRAM_TEXEL_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_RENDERBUFFER_SIZE [

	<generated>
	^ GL_MAX_RENDERBUFFER_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_SAMPLES [

	<generated>
	^ GL_MAX_SAMPLES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS [

	<generated>
	^ GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS [

	<generated>
	^ GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS [

	<generated>
	^ GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MAX_VARYING_COMPONENTS [

	<generated>
	^ GL_MAX_VARYING_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MINOR_VERSION [

	<generated>
	^ GL_MINOR_VERSION
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> MIN_PROGRAM_TEXEL_OFFSET [

	<generated>
	^ GL_MIN_PROGRAM_TEXEL_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> NUM_EXTENSIONS [

	<generated>
	^ GL_NUM_EXTENSIONS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> PRIMITIVES_GENERATED [

	<generated>
	^ GL_PRIMITIVES_GENERATED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> PROXY_TEXTURE_1D_ARRAY [

	<generated>
	^ GL_PROXY_TEXTURE_1D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> PROXY_TEXTURE_2D_ARRAY [

	<generated>
	^ GL_PROXY_TEXTURE_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> QUERY_BY_REGION_NO_WAIT [

	<generated>
	^ GL_QUERY_BY_REGION_NO_WAIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> QUERY_BY_REGION_WAIT [

	<generated>
	^ GL_QUERY_BY_REGION_WAIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> QUERY_NO_WAIT [

	<generated>
	^ GL_QUERY_NO_WAIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> QUERY_WAIT [

	<generated>
	^ GL_QUERY_WAIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R11F_G11F_B10F [

	<generated>
	^ GL_R11F_G11F_B10F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R16 [

	<generated>
	^ GL_R16
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R16F [

	<generated>
	^ GL_R16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R16I [

	<generated>
	^ GL_R16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R16UI [

	<generated>
	^ GL_R16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R32F [

	<generated>
	^ GL_R32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R32I [

	<generated>
	^ GL_R32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R32UI [

	<generated>
	^ GL_R32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R8 [

	<generated>
	^ GL_R8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R8I [

	<generated>
	^ GL_R8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> R8UI [

	<generated>
	^ GL_R8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RASTERIZER_DISCARD [

	<generated>
	^ GL_RASTERIZER_DISCARD
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> READ_FRAMEBUFFER [

	<generated>
	^ GL_READ_FRAMEBUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> READ_FRAMEBUFFER_BINDING [

	<generated>
	^ GL_READ_FRAMEBUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RED_INTEGER [

	<generated>
	^ GL_RED_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER [

	<generated>
	^ GL_RENDERBUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_ALPHA_SIZE [

	<generated>
	^ GL_RENDERBUFFER_ALPHA_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_BINDING [

	<generated>
	^ GL_RENDERBUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_BLUE_SIZE [

	<generated>
	^ GL_RENDERBUFFER_BLUE_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_DEPTH_SIZE [

	<generated>
	^ GL_RENDERBUFFER_DEPTH_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_GREEN_SIZE [

	<generated>
	^ GL_RENDERBUFFER_GREEN_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_HEIGHT [

	<generated>
	^ GL_RENDERBUFFER_HEIGHT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_INTERNAL_FORMAT [

	<generated>
	^ GL_RENDERBUFFER_INTERNAL_FORMAT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_RED_SIZE [

	<generated>
	^ GL_RENDERBUFFER_RED_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_SAMPLES [

	<generated>
	^ GL_RENDERBUFFER_SAMPLES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_STENCIL_SIZE [

	<generated>
	^ GL_RENDERBUFFER_STENCIL_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RENDERBUFFER_WIDTH [

	<generated>
	^ GL_RENDERBUFFER_WIDTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG [

	<generated>
	^ GL_RG
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG16 [

	<generated>
	^ GL_RG16
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG16F [

	<generated>
	^ GL_RG16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG16I [

	<generated>
	^ GL_RG16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG16UI [

	<generated>
	^ GL_RG16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG32F [

	<generated>
	^ GL_RG32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG32I [

	<generated>
	^ GL_RG32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG32UI [

	<generated>
	^ GL_RG32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG8 [

	<generated>
	^ GL_RG8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG8I [

	<generated>
	^ GL_RG8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG8UI [

	<generated>
	^ GL_RG8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB16F [

	<generated>
	^ GL_RGB16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB16I [

	<generated>
	^ GL_RGB16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB16UI [

	<generated>
	^ GL_RGB16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB32F [

	<generated>
	^ GL_RGB32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB32I [

	<generated>
	^ GL_RGB32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB32UI [

	<generated>
	^ GL_RGB32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB8I [

	<generated>
	^ GL_RGB8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB8UI [

	<generated>
	^ GL_RGB8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB9_E5 [

	<generated>
	^ GL_RGB9_E5
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA16F [

	<generated>
	^ GL_RGBA16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA16I [

	<generated>
	^ GL_RGBA16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA16UI [

	<generated>
	^ GL_RGBA16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA32F [

	<generated>
	^ GL_RGBA32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA32I [

	<generated>
	^ GL_RGBA32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA32UI [

	<generated>
	^ GL_RGBA32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA8I [

	<generated>
	^ GL_RGBA8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA8UI [

	<generated>
	^ GL_RGBA8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGBA_INTEGER [

	<generated>
	^ GL_RGBA_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RGB_INTEGER [

	<generated>
	^ GL_RGB_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> RG_INTEGER [

	<generated>
	^ GL_RG_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> SAMPLER_1D_ARRAY [

	<generated>
	^ GL_SAMPLER_1D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> SAMPLER_1D_ARRAY_SHADOW [

	<generated>
	^ GL_SAMPLER_1D_ARRAY_SHADOW
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> SAMPLER_2D_ARRAY [

	<generated>
	^ GL_SAMPLER_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> SAMPLER_2D_ARRAY_SHADOW [

	<generated>
	^ GL_SAMPLER_2D_ARRAY_SHADOW
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> SAMPLER_CUBE_SHADOW [

	<generated>
	^ GL_SAMPLER_CUBE_SHADOW
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> SEPARATE_ATTRIBS [

	<generated>
	^ GL_SEPARATE_ATTRIBS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> STENCIL_ATTACHMENT [

	<generated>
	^ GL_STENCIL_ATTACHMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> STENCIL_INDEX1 [

	<generated>
	^ GL_STENCIL_INDEX1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> STENCIL_INDEX16 [

	<generated>
	^ GL_STENCIL_INDEX16
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> STENCIL_INDEX4 [

	<generated>
	^ GL_STENCIL_INDEX4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> STENCIL_INDEX8 [

	<generated>
	^ GL_STENCIL_INDEX8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_1D_ARRAY [

	<generated>
	^ GL_TEXTURE_1D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_2D_ARRAY [

	<generated>
	^ GL_TEXTURE_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_ALPHA_TYPE [

	<generated>
	^ GL_TEXTURE_ALPHA_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_BINDING_1D_ARRAY [

	<generated>
	^ GL_TEXTURE_BINDING_1D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_BINDING_2D_ARRAY [

	<generated>
	^ GL_TEXTURE_BINDING_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_BLUE_TYPE [

	<generated>
	^ GL_TEXTURE_BLUE_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_DEPTH_TYPE [

	<generated>
	^ GL_TEXTURE_DEPTH_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_GREEN_TYPE [

	<generated>
	^ GL_TEXTURE_GREEN_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_INTENSITY_TYPE [

	<generated>
	^ GL_TEXTURE_INTENSITY_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_LUMINANCE_TYPE [

	<generated>
	^ GL_TEXTURE_LUMINANCE_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_RED_TYPE [

	<generated>
	^ GL_TEXTURE_RED_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_SHARED_SIZE [

	<generated>
	^ GL_TEXTURE_SHARED_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TEXTURE_STENCIL_SIZE [

	<generated>
	^ GL_TEXTURE_STENCIL_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_BUFFER [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_BUFFER_BINDING [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_BUFFER_MODE [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_MODE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_BUFFER_SIZE [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_BUFFER_START [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_START
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_VARYINGS [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_VARYINGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_10F_11F_11F_REV [

	<generated>
	^ GL_UNSIGNED_INT_10F_11F_11F_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_24_8 [

	<generated>
	^ GL_UNSIGNED_INT_24_8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_5_9_9_9_REV [

	<generated>
	^ GL_UNSIGNED_INT_5_9_9_9_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_SAMPLER_1D [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_1D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_SAMPLER_1D_ARRAY [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_1D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_SAMPLER_2D [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_2D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_SAMPLER_2D_ARRAY [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_SAMPLER_3D [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_SAMPLER_CUBE [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_CUBE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_VEC2 [

	<generated>
	^ GL_UNSIGNED_INT_VEC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_VEC3 [

	<generated>
	^ GL_UNSIGNED_INT_VEC3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_INT_VEC4 [

	<generated>
	^ GL_UNSIGNED_INT_VEC4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> UNSIGNED_NORMALIZED [

	<generated>
	^ GL_UNSIGNED_NORMALIZED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> VERTEX_ARRAY_BINDING [

	<generated>
	^ GL_VERTEX_ARRAY_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> VERTEX_ATTRIB_ARRAY_INTEGER [

	<generated>
	^ GL_VERTEX_ATTRIB_ARRAY_INTEGER
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> beginConditionalRender: id with: mode [

	<generated>
	<apicall: void 'glBeginConditionalRender' (GLuint GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> beginTransformFeedback: primitiveMode [

	<generated>
	<apicall: void 'glBeginTransformFeedback' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> bindBufferBase: target with: index with: buffer [

	<generated>
	<apicall: void 'glBindBufferBase' (GLenum GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> bindBufferRange: target with: index with: buffer with: offset with: size [

	<generated>
	<apicall: void 'glBindBufferRange' (GLenum GLuint GLuint GLintptr GLsizeiptr)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> bindFragDataLocation: program with: color with: name [

	<generated>
	<apicall: void 'glBindFragDataLocation' (GLuint GLuint GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> bindFramebuffer: target with: framebuffer [

	<generated>
	<apicall: void 'glBindFramebuffer' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> bindRenderbuffer: target with: renderbuffer [

	<generated>
	<apicall: void 'glBindRenderbuffer' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> bindVertexArray: array [

	<generated>
	<apicall: void 'glBindVertexArray' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> blitFramebuffer: srcX0 with: srcY0 with: srcX1 with: srcY1 with: dstX0 with: dstY0 with: dstX1 with: dstY1 with: mask with: filter [

	<generated>
	<apicall: void 'glBlitFramebuffer' (GLint GLint GLint GLint GLint GLint GLint GLint GLbitfield GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> checkFramebufferStatus: target [

	<generated>
	<apicall: GLenum 'glCheckFramebufferStatus' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> clampColor: target with: clamp [

	<generated>
	<apicall: void 'glClampColor' (GLenum GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> clearBufferfi: buffer with: drawbuffer with: depth with: stencil [

	<generated>
	<apicall: void 'glClearBufferfi' (GLenum GLint GLfloat GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> clearBufferfv: buffer with: drawbuffer with: value [

	<generated>
	<apicall: void 'glClearBufferfv' (GLenum GLint GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> clearBufferiv: buffer with: drawbuffer with: value [

	<generated>
	<apicall: void 'glClearBufferiv' (GLenum GLint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> clearBufferuiv: buffer with: drawbuffer with: value [

	<generated>
	<apicall: void 'glClearBufferuiv' (GLenum GLint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> colorMaski: index with: r with: g with: b with: a [

	<generated>
	<apicall: void 'glColorMaski' (GLuint GLboolean GLboolean GLboolean GLboolean)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> deleteFramebuffers: n with: framebuffers [

	<generated>
	<apicall: void 'glDeleteFramebuffers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> deleteRenderbuffers: n with: renderbuffers [

	<generated>
	<apicall: void 'glDeleteRenderbuffers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> deleteVertexArrays: n with: arrays [

	<generated>
	<apicall: void 'glDeleteVertexArrays' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> disablei: target with: index [

	<generated>
	<apicall: void 'glDisablei' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> enablei: target with: index [

	<generated>
	<apicall: void 'glEnablei' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> endConditionalRender [

	<generated>
	<apicall: void 'glEndConditionalRender' ()>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> endTransformFeedback [

	<generated>
	<apicall: void 'glEndTransformFeedback' ()>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> flushMappedBufferRange: target with: offset with: length [

	<generated>
	<apicall: void 'glFlushMappedBufferRange' (GLenum GLintptr GLsizeiptr)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> framebufferRenderbuffer: target with: attachment with: renderbuffertarget with: renderbuffer [

	<generated>
	<apicall: void 'glFramebufferRenderbuffer' (GLenum GLenum GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> framebufferTexture1D: target with: attachment with: textarget with: texture with: level [

	<generated>
	<apicall: void 'glFramebufferTexture1D' (GLenum GLenum GLenum GLuint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> framebufferTexture2D: target with: attachment with: textarget with: texture with: level [

	<generated>
	<apicall: void 'glFramebufferTexture2D' (GLenum GLenum GLenum GLuint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> framebufferTexture3D: target with: attachment with: textarget with: texture with: level with: zoffset [

	<generated>
	<apicall: void 'glFramebufferTexture3D' (GLenum GLenum GLenum GLuint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> framebufferTextureLayer: target with: attachment with: texture with: level with: layer [

	<generated>
	<apicall: void 'glFramebufferTextureLayer' (GLenum GLenum GLuint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> genFramebuffers: n with: framebuffers [

	<generated>
	<apicall: void 'glGenFramebuffers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> genRenderbuffers: n with: renderbuffers [

	<generated>
	<apicall: void 'glGenRenderbuffers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> genVertexArrays: n with: arrays [

	<generated>
	<apicall: void 'glGenVertexArrays' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> generateMipmap: target [

	<generated>
	<apicall: void 'glGenerateMipmap' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getBooleani_v: target with: index with: data [

	<generated>
	<apicall: void 'glGetBooleani_v' (GLenum GLuint GLboolean*)>
	^ self externalCallFailed
]

{
	#category : #parameters,
	#timestamp : 'stlu 11/12/2020 15:45'
}
GL3_0 >> getExtensions [

	| extensions |
	extensions := Array new: self getNumExtensions.
	1 to: extensions size do: [:i |
		extensions at: i put: (self getStringParameter: GL_EXTENSIONS at: i - 1)].
	^ extensions
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getFragDataLocation: program with: name [

	<generated>
	<apicall: GLint 'glGetFragDataLocation' (GLuint GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getFramebufferAttachmentParameteriv: target with: attachment with: pname with: params [

	<generated>
	<apicall: void 'glGetFramebufferAttachmentParameteriv' (GLenum GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getIntegeri_v: target with: index with: data [

	<generated>
	<apicall: void 'glGetIntegeri_v' (GLenum GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getRenderbufferParameteriv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetRenderbufferParameteriv' (GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getStringi: name with: index [

	<generated>
	<apicall: GLubyte* 'glGetStringi' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getTexParameterIiv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetTexParameterIiv' (GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getTexParameterIuiv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetTexParameterIuiv' (GLenum GLenum GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getTransformFeedbackVarying: program with: index with: bufSize with: length with: size with: type with: name [

	<generated>
	<apicall: void 'glGetTransformFeedbackVarying' (GLuint GLuint GLsizei GLsizei* GLsizei* GLenum* GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getUniformuiv: program with: location with: params [

	<generated>
	<apicall: void 'glGetUniformuiv' (GLuint GLint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getVertexAttribIiv: index with: pname with: params [

	<generated>
	<apicall: void 'glGetVertexAttribIiv' (GLuint GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> getVertexAttribIuiv: index with: pname with: params [

	<generated>
	<apicall: void 'glGetVertexAttribIuiv' (GLuint GLenum GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> isEnabledi: target with: index [

	<generated>
	<apicall: GLboolean 'glIsEnabledi' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> isFramebuffer: framebuffer [

	<generated>
	<apicall: GLboolean 'glIsFramebuffer' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> isRenderbuffer: renderbuffer [

	<generated>
	<apicall: GLboolean 'glIsRenderbuffer' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> isVertexArray: array [

	<generated>
	<apicall: GLboolean 'glIsVertexArray' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> mapBufferRange: target with: offset with: length with: access [

	<generated>
	<apicall: void* 'glMapBufferRange' (GLenum GLintptr GLsizeiptr GLbitfield)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> renderbufferStorage: target with: internalformat with: width with: height [

	<generated>
	<apicall: void 'glRenderbufferStorage' (GLenum GLenum GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> renderbufferStorageMultisample: target with: samples with: internalformat with: width with: height [

	<generated>
	<apicall: void 'glRenderbufferStorageMultisample' (GLenum GLsizei GLenum GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> texParameterIiv: target with: pname with: params [

	<generated>
	<apicall: void 'glTexParameterIiv' (GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> texParameterIuiv: target with: pname with: params [

	<generated>
	<apicall: void 'glTexParameterIuiv' (GLenum GLenum GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> transformFeedbackVaryings: program with: count with: varyings with: bufferMode [

	<generated>
	<apicall: void 'glTransformFeedbackVaryings' (GLuint GLsizei GLchar** GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform1ui: location with: v0 [

	<generated>
	<apicall: void 'glUniform1ui' (GLint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform1uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform1uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform2ui: location with: v0 with: v1 [

	<generated>
	<apicall: void 'glUniform2ui' (GLint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform2uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform2uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform3ui: location with: v0 with: v1 with: v2 [

	<generated>
	<apicall: void 'glUniform3ui' (GLint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform3uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform3uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform4ui: location with: v0 with: v1 with: v2 with: v3 [

	<generated>
	<apicall: void 'glUniform4ui' (GLint GLuint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> uniform4uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform4uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI1i: index with: x [

	<generated>
	<apicall: void 'glVertexAttribI1i' (GLuint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI1iv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI1iv' (GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI1ui: index with: x [

	<generated>
	<apicall: void 'glVertexAttribI1ui' (GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI1uiv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI1uiv' (GLuint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI2i: index with: x with: y [

	<generated>
	<apicall: void 'glVertexAttribI2i' (GLuint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI2iv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI2iv' (GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI2ui: index with: x with: y [

	<generated>
	<apicall: void 'glVertexAttribI2ui' (GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI2uiv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI2uiv' (GLuint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI3i: index with: x with: y with: z [

	<generated>
	<apicall: void 'glVertexAttribI3i' (GLuint GLint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI3iv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI3iv' (GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI3ui: index with: x with: y with: z [

	<generated>
	<apicall: void 'glVertexAttribI3ui' (GLuint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI3uiv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI3uiv' (GLuint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4bv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4bv' (GLuint GLbyte*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4i: index with: x with: y with: z with: w [

	<generated>
	<apicall: void 'glVertexAttribI4i' (GLuint GLint GLint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4iv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4iv' (GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4sv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4sv' (GLuint GLshort*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4ubv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4ubv' (GLuint GLubyte*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4ui: index with: x with: y with: z with: w [

	<generated>
	<apicall: void 'glVertexAttribI4ui' (GLuint GLuint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4uiv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4uiv' (GLuint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribI4usv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4usv' (GLuint GLushort*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 2/12/2021 00:43'
}
GL3_0 >> vertexAttribIPointer: index with: size with: type with: stride with: pointer [

	<generated>
	<apicall: void 'glVertexAttribIPointer' (GLuint GLint GLenum GLsizei void*)>
	^ self externalCallFailed
]
