Class {
	#name : #'GLES3_0',
	#superclass : #'GLES2_0',
	#category : #'OpenGL-API-GLES2',
	#commentStamp : ''
}

{
	#category : #accessing,
	#timestamp : ''
}
GLES3_0 class >> majorVersion [

	^ 3
]

{
	#category : #accessing,
	#timestamp : ''
}
GLES3_0 class >> minorVersion [

	^ 0
]

{
	#category : #accessing,
	#timestamp : 'stlu 11/2/2020 16:11'
}
GLES3_0 class >> versionNumber [

	^ 30
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> ACTIVE_UNIFORM_BLOCKS [

	<generated>
	^ GL_ACTIVE_UNIFORM_BLOCKS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH [

	<generated>
	^ GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> ALREADY_SIGNALED [

	<generated>
	^ GL_ALREADY_SIGNALED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> ANY_SAMPLES_PASSED [

	<generated>
	^ GL_ANY_SAMPLES_PASSED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> ANY_SAMPLES_PASSED_CONSERVATIVE [

	<generated>
	^ GL_ANY_SAMPLES_PASSED_CONSERVATIVE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> BLUE [

	<generated>
	^ GL_BLUE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> BUFFER_ACCESS_FLAGS [

	<generated>
	^ GL_BUFFER_ACCESS_FLAGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> BUFFER_MAPPED [

	<generated>
	^ GL_BUFFER_MAPPED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> BUFFER_MAP_LENGTH [

	<generated>
	^ GL_BUFFER_MAP_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> BUFFER_MAP_OFFSET [

	<generated>
	^ GL_BUFFER_MAP_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> BUFFER_MAP_POINTER [

	<generated>
	^ GL_BUFFER_MAP_POINTER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR [

	<generated>
	^ GL_COLOR
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT1 [

	<generated>
	^ GL_COLOR_ATTACHMENT1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT10 [

	<generated>
	^ GL_COLOR_ATTACHMENT10
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT11 [

	<generated>
	^ GL_COLOR_ATTACHMENT11
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT12 [

	<generated>
	^ GL_COLOR_ATTACHMENT12
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT13 [

	<generated>
	^ GL_COLOR_ATTACHMENT13
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT14 [

	<generated>
	^ GL_COLOR_ATTACHMENT14
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT15 [

	<generated>
	^ GL_COLOR_ATTACHMENT15
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT16 [

	<generated>
	^ GL_COLOR_ATTACHMENT16
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT17 [

	<generated>
	^ GL_COLOR_ATTACHMENT17
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT18 [

	<generated>
	^ GL_COLOR_ATTACHMENT18
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT19 [

	<generated>
	^ GL_COLOR_ATTACHMENT19
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT2 [

	<generated>
	^ GL_COLOR_ATTACHMENT2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT20 [

	<generated>
	^ GL_COLOR_ATTACHMENT20
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT21 [

	<generated>
	^ GL_COLOR_ATTACHMENT21
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT22 [

	<generated>
	^ GL_COLOR_ATTACHMENT22
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT23 [

	<generated>
	^ GL_COLOR_ATTACHMENT23
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT24 [

	<generated>
	^ GL_COLOR_ATTACHMENT24
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT25 [

	<generated>
	^ GL_COLOR_ATTACHMENT25
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT26 [

	<generated>
	^ GL_COLOR_ATTACHMENT26
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT27 [

	<generated>
	^ GL_COLOR_ATTACHMENT27
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT28 [

	<generated>
	^ GL_COLOR_ATTACHMENT28
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT29 [

	<generated>
	^ GL_COLOR_ATTACHMENT29
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT3 [

	<generated>
	^ GL_COLOR_ATTACHMENT3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT30 [

	<generated>
	^ GL_COLOR_ATTACHMENT30
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT31 [

	<generated>
	^ GL_COLOR_ATTACHMENT31
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT4 [

	<generated>
	^ GL_COLOR_ATTACHMENT4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT5 [

	<generated>
	^ GL_COLOR_ATTACHMENT5
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT6 [

	<generated>
	^ GL_COLOR_ATTACHMENT6
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT7 [

	<generated>
	^ GL_COLOR_ATTACHMENT7
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT8 [

	<generated>
	^ GL_COLOR_ATTACHMENT8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COLOR_ATTACHMENT9 [

	<generated>
	^ GL_COLOR_ATTACHMENT9
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPARE_REF_TO_TEXTURE [

	<generated>
	^ GL_COMPARE_REF_TO_TEXTURE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_R11_EAC [

	<generated>
	^ GL_COMPRESSED_R11_EAC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_RG11_EAC [

	<generated>
	^ GL_COMPRESSED_RG11_EAC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_RGB8_ETC2 [

	<generated>
	^ GL_COMPRESSED_RGB8_ETC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 [

	<generated>
	^ GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_RGBA8_ETC2_EAC [

	<generated>
	^ GL_COMPRESSED_RGBA8_ETC2_EAC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_SIGNED_R11_EAC [

	<generated>
	^ GL_COMPRESSED_SIGNED_R11_EAC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_SIGNED_RG11_EAC [

	<generated>
	^ GL_COMPRESSED_SIGNED_RG11_EAC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_SRGB8_ALPHA8_ETC2_EAC [

	<generated>
	^ GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_SRGB8_ETC2 [

	<generated>
	^ GL_COMPRESSED_SRGB8_ETC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 [

	<generated>
	^ GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> CONDITION_SATISFIED [

	<generated>
	^ GL_CONDITION_SATISFIED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COPY_READ_BUFFER [

	<generated>
	^ GL_COPY_READ_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COPY_READ_BUFFER_BINDING [

	<generated>
	^ GL_COPY_READ_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COPY_WRITE_BUFFER [

	<generated>
	^ GL_COPY_WRITE_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> COPY_WRITE_BUFFER_BINDING [

	<generated>
	^ GL_COPY_WRITE_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> CURRENT_QUERY [

	<generated>
	^ GL_CURRENT_QUERY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH [

	<generated>
	^ GL_DEPTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH24_STENCIL8 [

	<generated>
	^ GL_DEPTH24_STENCIL8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH32F_STENCIL8 [

	<generated>
	^ GL_DEPTH32F_STENCIL8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH_COMPONENT24 [

	<generated>
	^ GL_DEPTH_COMPONENT24
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH_COMPONENT32F [

	<generated>
	^ GL_DEPTH_COMPONENT32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH_STENCIL [

	<generated>
	^ GL_DEPTH_STENCIL
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DEPTH_STENCIL_ATTACHMENT [

	<generated>
	^ GL_DEPTH_STENCIL_ATTACHMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER0 [

	<generated>
	^ GL_DRAW_BUFFER0
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER1 [

	<generated>
	^ GL_DRAW_BUFFER1
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER10 [

	<generated>
	^ GL_DRAW_BUFFER10
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER11 [

	<generated>
	^ GL_DRAW_BUFFER11
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER12 [

	<generated>
	^ GL_DRAW_BUFFER12
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER13 [

	<generated>
	^ GL_DRAW_BUFFER13
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER14 [

	<generated>
	^ GL_DRAW_BUFFER14
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER15 [

	<generated>
	^ GL_DRAW_BUFFER15
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER2 [

	<generated>
	^ GL_DRAW_BUFFER2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER3 [

	<generated>
	^ GL_DRAW_BUFFER3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER4 [

	<generated>
	^ GL_DRAW_BUFFER4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER5 [

	<generated>
	^ GL_DRAW_BUFFER5
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER6 [

	<generated>
	^ GL_DRAW_BUFFER6
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER7 [

	<generated>
	^ GL_DRAW_BUFFER7
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER8 [

	<generated>
	^ GL_DRAW_BUFFER8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_BUFFER9 [

	<generated>
	^ GL_DRAW_BUFFER9
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_FRAMEBUFFER [

	<generated>
	^ GL_DRAW_FRAMEBUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DRAW_FRAMEBUFFER_BINDING [

	<generated>
	^ GL_DRAW_FRAMEBUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DYNAMIC_COPY [

	<generated>
	^ GL_DYNAMIC_COPY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> DYNAMIC_READ [

	<generated>
	^ GL_DYNAMIC_READ
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_32_UNSIGNED_INT_24_8_REV [

	<generated>
	^ GL_FLOAT_32_UNSIGNED_INT_24_8_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_MAT2x3 [

	<generated>
	^ GL_FLOAT_MAT2x3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_MAT2x4 [

	<generated>
	^ GL_FLOAT_MAT2x4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_MAT3x2 [

	<generated>
	^ GL_FLOAT_MAT3x2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_MAT3x4 [

	<generated>
	^ GL_FLOAT_MAT3x4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_MAT4x2 [

	<generated>
	^ GL_FLOAT_MAT4x2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FLOAT_MAT4x3 [

	<generated>
	^ GL_FLOAT_MAT4x3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAGMENT_SHADER_DERIVATIVE_HINT [

	<generated>
	^ GL_FRAGMENT_SHADER_DERIVATIVE_HINT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_BLUE_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_GREEN_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_RED_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER [

	<generated>
	^ GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_DEFAULT [

	<generated>
	^ GL_FRAMEBUFFER_DEFAULT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_INCOMPLETE_MULTISAMPLE [

	<generated>
	^ GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> FRAMEBUFFER_UNDEFINED [

	<generated>
	^ GL_FRAMEBUFFER_UNDEFINED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> GREEN [

	<generated>
	^ GL_GREEN
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> HALF_FLOAT [

	<generated>
	^ GL_HALF_FLOAT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INTERLEAVED_ATTRIBS [

	<generated>
	^ GL_INTERLEAVED_ATTRIBS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INT_2_10_10_10_REV [

	<generated>
	^ GL_INT_2_10_10_10_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INT_SAMPLER_2D [

	<generated>
	^ GL_INT_SAMPLER_2D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INT_SAMPLER_2D_ARRAY [

	<generated>
	^ GL_INT_SAMPLER_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INT_SAMPLER_3D [

	<generated>
	^ GL_INT_SAMPLER_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INT_SAMPLER_CUBE [

	<generated>
	^ GL_INT_SAMPLER_CUBE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> INVALID_INDEX [

	<generated>
	^ GL_INVALID_INDEX
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAJOR_VERSION [

	<generated>
	^ GL_MAJOR_VERSION
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAP_FLUSH_EXPLICIT_BIT [

	<generated>
	^ GL_MAP_FLUSH_EXPLICIT_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAP_INVALIDATE_BUFFER_BIT [

	<generated>
	^ GL_MAP_INVALIDATE_BUFFER_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAP_INVALIDATE_RANGE_BIT [

	<generated>
	^ GL_MAP_INVALIDATE_RANGE_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAP_READ_BIT [

	<generated>
	^ GL_MAP_READ_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAP_UNSYNCHRONIZED_BIT [

	<generated>
	^ GL_MAP_UNSYNCHRONIZED_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAP_WRITE_BIT [

	<generated>
	^ GL_MAP_WRITE_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX [

	<generated>
	^ GL_MAX
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_3D_TEXTURE_SIZE [

	<generated>
	^ GL_MAX_3D_TEXTURE_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_ARRAY_TEXTURE_LAYERS [

	<generated>
	^ GL_MAX_ARRAY_TEXTURE_LAYERS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_COLOR_ATTACHMENTS [

	<generated>
	^ GL_MAX_COLOR_ATTACHMENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS [

	<generated>
	^ GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_COMBINED_UNIFORM_BLOCKS [

	<generated>
	^ GL_MAX_COMBINED_UNIFORM_BLOCKS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS [

	<generated>
	^ GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_DRAW_BUFFERS [

	<generated>
	^ GL_MAX_DRAW_BUFFERS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_ELEMENTS_INDICES [

	<generated>
	^ GL_MAX_ELEMENTS_INDICES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_ELEMENTS_VERTICES [

	<generated>
	^ GL_MAX_ELEMENTS_VERTICES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_ELEMENT_INDEX [

	<generated>
	^ GL_MAX_ELEMENT_INDEX
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_FRAGMENT_INPUT_COMPONENTS [

	<generated>
	^ GL_MAX_FRAGMENT_INPUT_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_FRAGMENT_UNIFORM_BLOCKS [

	<generated>
	^ GL_MAX_FRAGMENT_UNIFORM_BLOCKS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_FRAGMENT_UNIFORM_COMPONENTS [

	<generated>
	^ GL_MAX_FRAGMENT_UNIFORM_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_PROGRAM_TEXEL_OFFSET [

	<generated>
	^ GL_MAX_PROGRAM_TEXEL_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_SAMPLES [

	<generated>
	^ GL_MAX_SAMPLES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_SERVER_WAIT_TIMEOUT [

	<generated>
	^ GL_MAX_SERVER_WAIT_TIMEOUT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_TEXTURE_LOD_BIAS [

	<generated>
	^ GL_MAX_TEXTURE_LOD_BIAS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS [

	<generated>
	^ GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS [

	<generated>
	^ GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS [

	<generated>
	^ GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_UNIFORM_BLOCK_SIZE [

	<generated>
	^ GL_MAX_UNIFORM_BLOCK_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_UNIFORM_BUFFER_BINDINGS [

	<generated>
	^ GL_MAX_UNIFORM_BUFFER_BINDINGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_VARYING_COMPONENTS [

	<generated>
	^ GL_MAX_VARYING_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_VERTEX_OUTPUT_COMPONENTS [

	<generated>
	^ GL_MAX_VERTEX_OUTPUT_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_VERTEX_UNIFORM_BLOCKS [

	<generated>
	^ GL_MAX_VERTEX_UNIFORM_BLOCKS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MAX_VERTEX_UNIFORM_COMPONENTS [

	<generated>
	^ GL_MAX_VERTEX_UNIFORM_COMPONENTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MIN [

	<generated>
	^ GL_MIN
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MINOR_VERSION [

	<generated>
	^ GL_MINOR_VERSION
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> MIN_PROGRAM_TEXEL_OFFSET [

	<generated>
	^ GL_MIN_PROGRAM_TEXEL_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> NUM_EXTENSIONS [

	<generated>
	^ GL_NUM_EXTENSIONS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> NUM_PROGRAM_BINARY_FORMATS [

	<generated>
	^ GL_NUM_PROGRAM_BINARY_FORMATS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> NUM_SAMPLE_COUNTS [

	<generated>
	^ GL_NUM_SAMPLE_COUNTS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> OBJECT_TYPE [

	<generated>
	^ GL_OBJECT_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PACK_ROW_LENGTH [

	<generated>
	^ GL_PACK_ROW_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PACK_SKIP_PIXELS [

	<generated>
	^ GL_PACK_SKIP_PIXELS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PACK_SKIP_ROWS [

	<generated>
	^ GL_PACK_SKIP_ROWS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PIXEL_PACK_BUFFER [

	<generated>
	^ GL_PIXEL_PACK_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PIXEL_PACK_BUFFER_BINDING [

	<generated>
	^ GL_PIXEL_PACK_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PIXEL_UNPACK_BUFFER [

	<generated>
	^ GL_PIXEL_UNPACK_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PIXEL_UNPACK_BUFFER_BINDING [

	<generated>
	^ GL_PIXEL_UNPACK_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PRIMITIVE_RESTART_FIXED_INDEX [

	<generated>
	^ GL_PRIMITIVE_RESTART_FIXED_INDEX
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PROGRAM_BINARY_FORMATS [

	<generated>
	^ GL_PROGRAM_BINARY_FORMATS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PROGRAM_BINARY_LENGTH [

	<generated>
	^ GL_PROGRAM_BINARY_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> PROGRAM_BINARY_RETRIEVABLE_HINT [

	<generated>
	^ GL_PROGRAM_BINARY_RETRIEVABLE_HINT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> QUERY_RESULT [

	<generated>
	^ GL_QUERY_RESULT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> QUERY_RESULT_AVAILABLE [

	<generated>
	^ GL_QUERY_RESULT_AVAILABLE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R11F_G11F_B10F [

	<generated>
	^ GL_R11F_G11F_B10F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R16F [

	<generated>
	^ GL_R16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R16I [

	<generated>
	^ GL_R16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R16UI [

	<generated>
	^ GL_R16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R32F [

	<generated>
	^ GL_R32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R32I [

	<generated>
	^ GL_R32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R32UI [

	<generated>
	^ GL_R32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R8 [

	<generated>
	^ GL_R8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R8I [

	<generated>
	^ GL_R8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R8UI [

	<generated>
	^ GL_R8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> R8_SNORM [

	<generated>
	^ GL_R8_SNORM
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RASTERIZER_DISCARD [

	<generated>
	^ GL_RASTERIZER_DISCARD
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> READ_BUFFER [

	<generated>
	^ GL_READ_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> READ_FRAMEBUFFER [

	<generated>
	^ GL_READ_FRAMEBUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> READ_FRAMEBUFFER_BINDING [

	<generated>
	^ GL_READ_FRAMEBUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RED [

	<generated>
	^ GL_RED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RED_INTEGER [

	<generated>
	^ GL_RED_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RENDERBUFFER_SAMPLES [

	<generated>
	^ GL_RENDERBUFFER_SAMPLES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG [

	<generated>
	^ GL_RG
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG16F [

	<generated>
	^ GL_RG16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG16I [

	<generated>
	^ GL_RG16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG16UI [

	<generated>
	^ GL_RG16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG32F [

	<generated>
	^ GL_RG32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG32I [

	<generated>
	^ GL_RG32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG32UI [

	<generated>
	^ GL_RG32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG8 [

	<generated>
	^ GL_RG8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG8I [

	<generated>
	^ GL_RG8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG8UI [

	<generated>
	^ GL_RG8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG8_SNORM [

	<generated>
	^ GL_RG8_SNORM
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB10_A2 [

	<generated>
	^ GL_RGB10_A2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB10_A2UI [

	<generated>
	^ GL_RGB10_A2UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB16F [

	<generated>
	^ GL_RGB16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB16I [

	<generated>
	^ GL_RGB16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB16UI [

	<generated>
	^ GL_RGB16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB32F [

	<generated>
	^ GL_RGB32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB32I [

	<generated>
	^ GL_RGB32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB32UI [

	<generated>
	^ GL_RGB32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB8 [

	<generated>
	^ GL_RGB8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB8I [

	<generated>
	^ GL_RGB8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB8UI [

	<generated>
	^ GL_RGB8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB8_SNORM [

	<generated>
	^ GL_RGB8_SNORM
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB9_E5 [

	<generated>
	^ GL_RGB9_E5
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA16F [

	<generated>
	^ GL_RGBA16F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA16I [

	<generated>
	^ GL_RGBA16I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA16UI [

	<generated>
	^ GL_RGBA16UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA32F [

	<generated>
	^ GL_RGBA32F
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA32I [

	<generated>
	^ GL_RGBA32I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA32UI [

	<generated>
	^ GL_RGBA32UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA8 [

	<generated>
	^ GL_RGBA8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA8I [

	<generated>
	^ GL_RGBA8I
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA8UI [

	<generated>
	^ GL_RGBA8UI
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA8_SNORM [

	<generated>
	^ GL_RGBA8_SNORM
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGBA_INTEGER [

	<generated>
	^ GL_RGBA_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RGB_INTEGER [

	<generated>
	^ GL_RGB_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> RG_INTEGER [

	<generated>
	^ GL_RG_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SAMPLER_2D_ARRAY [

	<generated>
	^ GL_SAMPLER_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SAMPLER_2D_ARRAY_SHADOW [

	<generated>
	^ GL_SAMPLER_2D_ARRAY_SHADOW
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SAMPLER_2D_SHADOW [

	<generated>
	^ GL_SAMPLER_2D_SHADOW
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SAMPLER_3D [

	<generated>
	^ GL_SAMPLER_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SAMPLER_BINDING [

	<generated>
	^ GL_SAMPLER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SAMPLER_CUBE_SHADOW [

	<generated>
	^ GL_SAMPLER_CUBE_SHADOW
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SEPARATE_ATTRIBS [

	<generated>
	^ GL_SEPARATE_ATTRIBS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SIGNALED [

	<generated>
	^ GL_SIGNALED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SIGNED_NORMALIZED [

	<generated>
	^ GL_SIGNED_NORMALIZED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SRGB [

	<generated>
	^ GL_SRGB
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SRGB8 [

	<generated>
	^ GL_SRGB8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SRGB8_ALPHA8 [

	<generated>
	^ GL_SRGB8_ALPHA8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> STATIC_COPY [

	<generated>
	^ GL_STATIC_COPY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> STATIC_READ [

	<generated>
	^ GL_STATIC_READ
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> STENCIL [

	<generated>
	^ GL_STENCIL
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> STREAM_COPY [

	<generated>
	^ GL_STREAM_COPY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> STREAM_READ [

	<generated>
	^ GL_STREAM_READ
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SYNC_CONDITION [

	<generated>
	^ GL_SYNC_CONDITION
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SYNC_FENCE [

	<generated>
	^ GL_SYNC_FENCE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SYNC_FLAGS [

	<generated>
	^ GL_SYNC_FLAGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SYNC_FLUSH_COMMANDS_BIT [

	<generated>
	^ GL_SYNC_FLUSH_COMMANDS_BIT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SYNC_GPU_COMMANDS_COMPLETE [

	<generated>
	^ GL_SYNC_GPU_COMMANDS_COMPLETE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> SYNC_STATUS [

	<generated>
	^ GL_SYNC_STATUS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_2D_ARRAY [

	<generated>
	^ GL_TEXTURE_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_3D [

	<generated>
	^ GL_TEXTURE_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_BASE_LEVEL [

	<generated>
	^ GL_TEXTURE_BASE_LEVEL
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_BINDING_2D_ARRAY [

	<generated>
	^ GL_TEXTURE_BINDING_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_BINDING_3D [

	<generated>
	^ GL_TEXTURE_BINDING_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_COMPARE_FUNC [

	<generated>
	^ GL_TEXTURE_COMPARE_FUNC
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_COMPARE_MODE [

	<generated>
	^ GL_TEXTURE_COMPARE_MODE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_IMMUTABLE_FORMAT [

	<generated>
	^ GL_TEXTURE_IMMUTABLE_FORMAT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_IMMUTABLE_LEVELS [

	<generated>
	^ GL_TEXTURE_IMMUTABLE_LEVELS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_MAX_LEVEL [

	<generated>
	^ GL_TEXTURE_MAX_LEVEL
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_MAX_LOD [

	<generated>
	^ GL_TEXTURE_MAX_LOD
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_MIN_LOD [

	<generated>
	^ GL_TEXTURE_MIN_LOD
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_SWIZZLE_A [

	<generated>
	^ GL_TEXTURE_SWIZZLE_A
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_SWIZZLE_B [

	<generated>
	^ GL_TEXTURE_SWIZZLE_B
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_SWIZZLE_G [

	<generated>
	^ GL_TEXTURE_SWIZZLE_G
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_SWIZZLE_R [

	<generated>
	^ GL_TEXTURE_SWIZZLE_R
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TEXTURE_WRAP_R [

	<generated>
	^ GL_TEXTURE_WRAP_R
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TIMEOUT_EXPIRED [

	<generated>
	^ GL_TIMEOUT_EXPIRED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TIMEOUT_IGNORED [

	<generated>
	^ GL_TIMEOUT_IGNORED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK [

	<generated>
	^ GL_TRANSFORM_FEEDBACK
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_ACTIVE [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_ACTIVE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_BINDING [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_BUFFER [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_BUFFER_BINDING [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_BUFFER_MODE [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_MODE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_BUFFER_SIZE [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_BUFFER_START [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_BUFFER_START
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_PAUSED [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_PAUSED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_VARYINGS [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_VARYINGS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH [

	<generated>
	^ GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_ARRAY_STRIDE [

	<generated>
	^ GL_UNIFORM_ARRAY_STRIDE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_ACTIVE_UNIFORMS [

	<generated>
	^ GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES [

	<generated>
	^ GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_BINDING [

	<generated>
	^ GL_UNIFORM_BLOCK_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_DATA_SIZE [

	<generated>
	^ GL_UNIFORM_BLOCK_DATA_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_INDEX [

	<generated>
	^ GL_UNIFORM_BLOCK_INDEX
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_NAME_LENGTH [

	<generated>
	^ GL_UNIFORM_BLOCK_NAME_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER [

	<generated>
	^ GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER [

	<generated>
	^ GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BUFFER [

	<generated>
	^ GL_UNIFORM_BUFFER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BUFFER_BINDING [

	<generated>
	^ GL_UNIFORM_BUFFER_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BUFFER_OFFSET_ALIGNMENT [

	<generated>
	^ GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BUFFER_SIZE [

	<generated>
	^ GL_UNIFORM_BUFFER_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_BUFFER_START [

	<generated>
	^ GL_UNIFORM_BUFFER_START
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_IS_ROW_MAJOR [

	<generated>
	^ GL_UNIFORM_IS_ROW_MAJOR
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_MATRIX_STRIDE [

	<generated>
	^ GL_UNIFORM_MATRIX_STRIDE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_NAME_LENGTH [

	<generated>
	^ GL_UNIFORM_NAME_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_OFFSET [

	<generated>
	^ GL_UNIFORM_OFFSET
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_SIZE [

	<generated>
	^ GL_UNIFORM_SIZE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNIFORM_TYPE [

	<generated>
	^ GL_UNIFORM_TYPE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNPACK_IMAGE_HEIGHT [

	<generated>
	^ GL_UNPACK_IMAGE_HEIGHT
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNPACK_ROW_LENGTH [

	<generated>
	^ GL_UNPACK_ROW_LENGTH
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNPACK_SKIP_IMAGES [

	<generated>
	^ GL_UNPACK_SKIP_IMAGES
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNPACK_SKIP_PIXELS [

	<generated>
	^ GL_UNPACK_SKIP_PIXELS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNPACK_SKIP_ROWS [

	<generated>
	^ GL_UNPACK_SKIP_ROWS
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNALED [

	<generated>
	^ GL_UNSIGNALED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_10F_11F_11F_REV [

	<generated>
	^ GL_UNSIGNED_INT_10F_11F_11F_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_24_8 [

	<generated>
	^ GL_UNSIGNED_INT_24_8
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_2_10_10_10_REV [

	<generated>
	^ GL_UNSIGNED_INT_2_10_10_10_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_5_9_9_9_REV [

	<generated>
	^ GL_UNSIGNED_INT_5_9_9_9_REV
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_SAMPLER_2D [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_2D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_SAMPLER_2D_ARRAY [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_2D_ARRAY
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_SAMPLER_3D [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_3D
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_SAMPLER_CUBE [

	<generated>
	^ GL_UNSIGNED_INT_SAMPLER_CUBE
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_VEC2 [

	<generated>
	^ GL_UNSIGNED_INT_VEC2
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_VEC3 [

	<generated>
	^ GL_UNSIGNED_INT_VEC3
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_INT_VEC4 [

	<generated>
	^ GL_UNSIGNED_INT_VEC4
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> UNSIGNED_NORMALIZED [

	<generated>
	^ GL_UNSIGNED_NORMALIZED
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> VERTEX_ARRAY_BINDING [

	<generated>
	^ GL_VERTEX_ARRAY_BINDING
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> VERTEX_ATTRIB_ARRAY_DIVISOR [

	<generated>
	^ GL_VERTEX_ATTRIB_ARRAY_DIVISOR
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> VERTEX_ATTRIB_ARRAY_INTEGER [

	<generated>
	^ GL_VERTEX_ATTRIB_ARRAY_INTEGER
]

{
	#category : #'constants - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> WAIT_FAILED [

	<generated>
	^ GL_WAIT_FAILED
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> beginQuery: target with: id [

	<generated>
	<apicall: void 'glBeginQuery' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> beginTransformFeedback: primitiveMode [

	<generated>
	<apicall: void 'glBeginTransformFeedback' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> bindBufferBase: target with: index with: buffer [

	<generated>
	<apicall: void 'glBindBufferBase' (GLenum GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> bindBufferRange: target with: index with: buffer with: offset with: size [

	<generated>
	<apicall: void 'glBindBufferRange' (GLenum GLuint GLuint GLintptr GLsizeiptr)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> bindSampler: unit with: sampler [

	<generated>
	<apicall: void 'glBindSampler' (GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> bindTransformFeedback: target with: id [

	<generated>
	<apicall: void 'glBindTransformFeedback' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> bindVertexArray: array [

	<generated>
	<apicall: void 'glBindVertexArray' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> blitFramebuffer: srcX0 with: srcY0 with: srcX1 with: srcY1 with: dstX0 with: dstY0 with: dstX1 with: dstY1 with: mask with: filter [

	<generated>
	<apicall: void 'glBlitFramebuffer' (GLint GLint GLint GLint GLint GLint GLint GLint GLbitfield GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> clearBufferfi: buffer with: drawbuffer with: depth with: stencil [

	<generated>
	<apicall: void 'glClearBufferfi' (GLenum GLint GLfloat GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> clearBufferfv: buffer with: drawbuffer with: value [

	<generated>
	<apicall: void 'glClearBufferfv' (GLenum GLint GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> clearBufferiv: buffer with: drawbuffer with: value [

	<generated>
	<apicall: void 'glClearBufferiv' (GLenum GLint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> clearBufferuiv: buffer with: drawbuffer with: value [

	<generated>
	<apicall: void 'glClearBufferuiv' (GLenum GLint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> clientWaitSync: sync with: flags with: timeout [

	<generated>
	<apicall: GLenum 'glClientWaitSync' (GLsync GLbitfield GLuint64)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> compressedTexImage3D: target with: level with: internalformat with: width with: height with: depth with: border with: imageSize with: data [

	<generated>
	<apicall: void 'glCompressedTexImage3D' (GLenum GLint GLenum GLsizei GLsizei GLsizei GLint GLsizei void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> compressedTexSubImage3D: target with: level with: xoffset with: yoffset with: zoffset with: width with: height with: depth with: format with: imageSize with: data [

	<generated>
	<apicall: void 'glCompressedTexSubImage3D' (GLenum GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLsizei void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> copyBufferSubData: readTarget with: writeTarget with: readOffset with: writeOffset with: size [

	<generated>
	<apicall: void 'glCopyBufferSubData' (GLenum GLenum GLintptr GLintptr GLsizeiptr)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> copyTexSubImage3D: target with: level with: xoffset with: yoffset with: zoffset with: x with: y with: width with: height [

	<generated>
	<apicall: void 'glCopyTexSubImage3D' (GLenum GLint GLint GLint GLint GLint GLint GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> deleteQueries: n with: ids [

	<generated>
	<apicall: void 'glDeleteQueries' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> deleteSamplers: count with: samplers [

	<generated>
	<apicall: void 'glDeleteSamplers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> deleteSync: sync [

	<generated>
	<apicall: void 'glDeleteSync' (GLsync)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> deleteTransformFeedbacks: n with: ids [

	<generated>
	<apicall: void 'glDeleteTransformFeedbacks' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> deleteVertexArrays: n with: arrays [

	<generated>
	<apicall: void 'glDeleteVertexArrays' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> drawArraysInstanced: mode with: first with: count with: instancecount [

	<generated>
	<apicall: void 'glDrawArraysInstanced' (GLenum GLint GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> drawBuffers: n with: bufs [

	<generated>
	<apicall: void 'glDrawBuffers' (GLsizei GLenum*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> drawElementsInstanced: mode with: count with: type with: indices with: instancecount [

	<generated>
	<apicall: void 'glDrawElementsInstanced' (GLenum GLsizei GLenum void* GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> drawRangeElements: mode with: start with: end with: count with: type with: indices [

	<generated>
	<apicall: void 'glDrawRangeElements' (GLenum GLuint GLuint GLsizei GLenum void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> endQuery: target [

	<generated>
	<apicall: void 'glEndQuery' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> endTransformFeedback [

	<generated>
	<apicall: void 'glEndTransformFeedback' ()>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> fenceSync: condition with: flags [

	<generated>
	<apicall: GLsync 'glFenceSync' (GLenum GLbitfield)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> flushMappedBufferRange: target with: offset with: length [

	<generated>
	<apicall: void 'glFlushMappedBufferRange' (GLenum GLintptr GLsizeiptr)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> framebufferTextureLayer: target with: attachment with: texture with: level with: layer [

	<generated>
	<apicall: void 'glFramebufferTextureLayer' (GLenum GLenum GLuint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> genQueries: n with: ids [

	<generated>
	<apicall: void 'glGenQueries' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> genSamplers: count with: samplers [

	<generated>
	<apicall: void 'glGenSamplers' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> genTransformFeedbacks: n with: ids [

	<generated>
	<apicall: void 'glGenTransformFeedbacks' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> genVertexArrays: n with: arrays [

	<generated>
	<apicall: void 'glGenVertexArrays' (GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getActiveUniformBlockName: program with: uniformBlockIndex with: bufSize with: length with: uniformBlockName [

	<generated>
	<apicall: void 'glGetActiveUniformBlockName' (GLuint GLuint GLsizei GLsizei* GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getActiveUniformBlockiv: program with: uniformBlockIndex with: pname with: params [

	<generated>
	<apicall: void 'glGetActiveUniformBlockiv' (GLuint GLuint GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getActiveUniformsiv: program with: uniformCount with: uniformIndices with: pname with: params [

	<generated>
	<apicall: void 'glGetActiveUniformsiv' (GLuint GLsizei GLuint* GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getBufferParameteri64v: target with: pname with: params [

	<generated>
	<apicall: void 'glGetBufferParameteri64v' (GLenum GLenum GLint64*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getBufferPointerv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetBufferPointerv' (GLenum GLenum void**)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getFragDataLocation: program with: name [

	<generated>
	<apicall: GLint 'glGetFragDataLocation' (GLuint GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getInteger64i_v: target with: index with: data [

	<generated>
	<apicall: void 'glGetInteger64i_v' (GLenum GLuint GLint64*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getInteger64v: pname with: data [

	<generated>
	<apicall: void 'glGetInteger64v' (GLenum GLint64*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getIntegeri_v: target with: index with: data [

	<generated>
	<apicall: void 'glGetIntegeri_v' (GLenum GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getInternalformativ: target with: internalformat with: pname with: count with: params [

	<generated>
	<apicall: void 'glGetInternalformativ' (GLenum GLenum GLenum GLsizei GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getProgramBinary: program with: bufSize with: length with: binaryFormat with: binary [

	<generated>
	<apicall: void 'glGetProgramBinary' (GLuint GLsizei GLsizei* GLenum* void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getQueryObjectuiv: id with: pname with: params [

	<generated>
	<apicall: void 'glGetQueryObjectuiv' (GLuint GLenum GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getQueryiv: target with: pname with: params [

	<generated>
	<apicall: void 'glGetQueryiv' (GLenum GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getSamplerParameterfv: sampler with: pname with: params [

	<generated>
	<apicall: void 'glGetSamplerParameterfv' (GLuint GLenum GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getSamplerParameteriv: sampler with: pname with: params [

	<generated>
	<apicall: void 'glGetSamplerParameteriv' (GLuint GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getStringi: name with: index [

	<generated>
	<apicall: GLubyte* 'glGetStringi' (GLenum GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getSynciv: sync with: pname with: count with: length with: values [

	<generated>
	<apicall: void 'glGetSynciv' (GLsync GLenum GLsizei GLsizei* GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getTransformFeedbackVarying: program with: index with: bufSize with: length with: size with: type with: name [

	<generated>
	<apicall: void 'glGetTransformFeedbackVarying' (GLuint GLuint GLsizei GLsizei* GLsizei* GLenum* GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getUniformBlockIndex: program with: uniformBlockName [

	<generated>
	<apicall: GLuint 'glGetUniformBlockIndex' (GLuint GLchar*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getUniformIndices: program with: uniformCount with: uniformNames with: uniformIndices [

	<generated>
	<apicall: void 'glGetUniformIndices' (GLuint GLsizei GLchar** GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getUniformuiv: program with: location with: params [

	<generated>
	<apicall: void 'glGetUniformuiv' (GLuint GLint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getVertexAttribIiv: index with: pname with: params [

	<generated>
	<apicall: void 'glGetVertexAttribIiv' (GLuint GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> getVertexAttribIuiv: index with: pname with: params [

	<generated>
	<apicall: void 'glGetVertexAttribIuiv' (GLuint GLenum GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> invalidateFramebuffer: target with: numAttachments with: attachments [

	<generated>
	<apicall: void 'glInvalidateFramebuffer' (GLenum GLsizei GLenum*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> invalidateSubFramebuffer: target with: numAttachments with: attachments with: x with: y with: width with: height [

	<generated>
	<apicall: void 'glInvalidateSubFramebuffer' (GLenum GLsizei GLenum* GLint GLint GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> isQuery: id [

	<generated>
	<apicall: GLboolean 'glIsQuery' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> isSampler: sampler [

	<generated>
	<apicall: GLboolean 'glIsSampler' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> isSync: sync [

	<generated>
	<apicall: GLboolean 'glIsSync' (GLsync)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> isTransformFeedback: id [

	<generated>
	<apicall: GLboolean 'glIsTransformFeedback' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> isVertexArray: array [

	<generated>
	<apicall: GLboolean 'glIsVertexArray' (GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> mapBufferRange: target with: offset with: length with: access [

	<generated>
	<apicall: void* 'glMapBufferRange' (GLenum GLintptr GLsizeiptr GLbitfield)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> pauseTransformFeedback [

	<generated>
	<apicall: void 'glPauseTransformFeedback' ()>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> programBinary: program with: binaryFormat with: binary with: length [

	<generated>
	<apicall: void 'glProgramBinary' (GLuint GLenum void* GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> programParameteri: program with: pname with: value [

	<generated>
	<apicall: void 'glProgramParameteri' (GLuint GLenum GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> readBuffer: src [

	<generated>
	<apicall: void 'glReadBuffer' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> renderbufferStorageMultisample: target with: samples with: internalformat with: width with: height [

	<generated>
	<apicall: void 'glRenderbufferStorageMultisample' (GLenum GLsizei GLenum GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> resumeTransformFeedback [

	<generated>
	<apicall: void 'glResumeTransformFeedback' ()>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> samplerParameterf: sampler with: pname with: param [

	<generated>
	<apicall: void 'glSamplerParameterf' (GLuint GLenum GLfloat)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> samplerParameterfv: sampler with: pname with: param [

	<generated>
	<apicall: void 'glSamplerParameterfv' (GLuint GLenum GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> samplerParameteri: sampler with: pname with: param [

	<generated>
	<apicall: void 'glSamplerParameteri' (GLuint GLenum GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> samplerParameteriv: sampler with: pname with: param [

	<generated>
	<apicall: void 'glSamplerParameteriv' (GLuint GLenum GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> texImage3D: target with: level with: internalformat with: width with: height with: depth with: border with: format with: type with: pixels [

	<generated>
	<apicall: void 'glTexImage3D' (GLenum GLint GLint GLsizei GLsizei GLsizei GLint GLenum GLenum void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> texStorage2D: target with: levels with: internalformat with: width with: height [

	<generated>
	<apicall: void 'glTexStorage2D' (GLenum GLsizei GLenum GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> texStorage3D: target with: levels with: internalformat with: width with: height with: depth [

	<generated>
	<apicall: void 'glTexStorage3D' (GLenum GLsizei GLenum GLsizei GLsizei GLsizei)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> texSubImage3D: target with: level with: xoffset with: yoffset with: zoffset with: width with: height with: depth with: format with: type with: pixels [

	<generated>
	<apicall: void 'glTexSubImage3D' (GLenum GLint GLint GLint GLint GLsizei GLsizei GLsizei GLenum GLenum void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> transformFeedbackVaryings: program with: count with: varyings with: bufferMode [

	<generated>
	<apicall: void 'glTransformFeedbackVaryings' (GLuint GLsizei GLchar** GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform1ui: location with: v0 [

	<generated>
	<apicall: void 'glUniform1ui' (GLint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform1uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform1uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform2ui: location with: v0 with: v1 [

	<generated>
	<apicall: void 'glUniform2ui' (GLint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform2uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform2uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform3ui: location with: v0 with: v1 with: v2 [

	<generated>
	<apicall: void 'glUniform3ui' (GLint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform3uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform3uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform4ui: location with: v0 with: v1 with: v2 with: v3 [

	<generated>
	<apicall: void 'glUniform4ui' (GLint GLuint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniform4uiv: location with: count with: value [

	<generated>
	<apicall: void 'glUniform4uiv' (GLint GLsizei GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformBlockBinding: program with: uniformBlockIndex with: uniformBlockBinding [

	<generated>
	<apicall: void 'glUniformBlockBinding' (GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformMatrix2x3fv: location with: count with: transpose with: value [

	<generated>
	<apicall: void 'glUniformMatrix2x3fv' (GLint GLsizei GLboolean GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformMatrix2x4fv: location with: count with: transpose with: value [

	<generated>
	<apicall: void 'glUniformMatrix2x4fv' (GLint GLsizei GLboolean GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformMatrix3x2fv: location with: count with: transpose with: value [

	<generated>
	<apicall: void 'glUniformMatrix3x2fv' (GLint GLsizei GLboolean GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformMatrix3x4fv: location with: count with: transpose with: value [

	<generated>
	<apicall: void 'glUniformMatrix3x4fv' (GLint GLsizei GLboolean GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformMatrix4x2fv: location with: count with: transpose with: value [

	<generated>
	<apicall: void 'glUniformMatrix4x2fv' (GLint GLsizei GLboolean GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> uniformMatrix4x3fv: location with: count with: transpose with: value [

	<generated>
	<apicall: void 'glUniformMatrix4x3fv' (GLint GLsizei GLboolean GLfloat*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> unmapBuffer: target [

	<generated>
	<apicall: GLboolean 'glUnmapBuffer' (GLenum)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> vertexAttribDivisor: index with: divisor [

	<generated>
	<apicall: void 'glVertexAttribDivisor' (GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> vertexAttribI4i: index with: x with: y with: z with: w [

	<generated>
	<apicall: void 'glVertexAttribI4i' (GLuint GLint GLint GLint GLint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> vertexAttribI4iv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4iv' (GLuint GLint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> vertexAttribI4ui: index with: x with: y with: z with: w [

	<generated>
	<apicall: void 'glVertexAttribI4ui' (GLuint GLuint GLuint GLuint GLuint)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> vertexAttribI4uiv: index with: v [

	<generated>
	<apicall: void 'glVertexAttribI4uiv' (GLuint GLuint*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> vertexAttribIPointer: index with: size with: type with: stride with: pointer [

	<generated>
	<apicall: void 'glVertexAttribIPointer' (GLuint GLint GLenum GLsizei void*)>
	^ self externalCallFailed
]

{
	#category : #'api - required',
	#timestamp : 'stlu 11/3/2020 14:57'
}
GLES3_0 >> waitSync: sync with: flags with: timeout [

	<generated>
	<apicall: void 'glWaitSync' (GLsync GLbitfield GLuint64)>
	^ self externalCallFailed
]
