Class {
	#name : #GLUniform,
	#superclass : #GLProgramResource,
	#instVars : [
		'type'
	],
	#category : #'OpenGL-Wrappers-Shaders',
	#commentStamp : ''
}

{
	#category : #'instance creation',
	#timestamp : 'stlu 10/28/2020 13:00'
}
GLUniform class >> program: glProgram index: anInteger [

	self notYetImplemented
]

{
	#category : #'instance creation',
	#timestamp : 'stlu 10/28/2020 12:58'
}
GLUniform class >> program: glProgram name: aString [

	self notYetImplemented
]
