Class {
	#name : #GLUniform,
	#superclass : #GLProgramResource,
	#category : #'OpenGL-Wrappers-Shaders',
	#commentStamp : ''
}

{
	#category : #'instance creation',
	#timestamp : ''
}
GLUniform class >> program: glProgram index: anInteger [

	self notYetImplemented
]

{
	#category : #'instance creation',
	#timestamp : ''
}
GLUniform class >> program: glProgram name: aString [

	self notYetImplemented
]
