as yet unclassified
fields

	^ #(
		(sType 'VkStructureType')
		(pNext 'void*')
		(flags 'VkSubpassDescriptionFlags')
		(pipelineBindPoint 'VkPipelineBindPoint')
		(viewMask 'uint32_t')
		(inputAttachmentCount 'uint32_t')
		(pInputAttachments 'VkAttachmentReference2*')
		(colorAttachmentCount 'uint32_t')
		(pColorAttachments 'VkAttachmentReference2*')
		(pResolveAttachments 'VkAttachmentReference2*')
		(pDepthStencilAttachment 'VkAttachmentReference2*')
		(preserveAttachmentCount 'uint32_t')
		(pPreserveAttachments 'uint32_t*')
	)