Extension { #name : #RawBitsArray }

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:22'
}
RawBitsArray >> startingAt: index put: value1 put: value2 [

	self at: index put: value1.
	self at: index + 1 put: value2.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:22'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/23/2021 15:04'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:23'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/23/2021 15:05'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:24'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/23/2021 15:05'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:25'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
	self at: index + 8 put: value9.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:25'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
	self at: index + 8 put: value9.
	self at: index + 9 put: value10.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:25'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
	self at: index + 8 put: value9.
	self at: index + 9 put: value10.
	self at: index + 10 put: value11.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/23/2021 15:05'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 put: value12 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
	self at: index + 8 put: value9.
	self at: index + 9 put: value10.
	self at: index + 10 put: value11.
	self at: index + 11 put: value12.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:25'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 put: value12 put: value13 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
	self at: index + 8 put: value9.
	self at: index + 9 put: value10.
	self at: index + 10 put: value11.
	self at: index + 11 put: value12.
	self at: index + 12 put: value13.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 8/27/2021 08:26'
}
RawBitsArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 put: value12 put: value13 put: value14 [

	self at: index put: value1.
	self at: index + 1 put: value2.
	self at: index + 2 put: value3.
	self at: index + 3 put: value4.
	self at: index + 4 put: value5.
	self at: index + 5 put: value6.
	self at: index + 6 put: value7.
	self at: index + 7 put: value8.
	self at: index + 8 put: value9.
	self at: index + 9 put: value10.
	self at: index + 10 put: value11.
	self at: index + 11 put: value12.
	self at: index + 12 put: value13.
	self at: index + 13 put: value14.
]
