Extension { #name : #SignedDoubleWordArray }

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 [

	<primitive: 'primitiveInt64StartingAtPut2' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 [

	<primitive: 'primitiveInt64StartingAtPut3' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 [

	<primitive: 'primitiveInt64StartingAtPut4' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 [

	<primitive: 'primitiveInt64StartingAtPut5' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 [

	<primitive: 'primitiveInt64StartingAtPut6' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 [

	<primitive: 'primitiveInt64StartingAtPut7' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 [

	<primitive: 'primitiveInt64StartingAtPut8' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 [

	<primitive: 'primitiveInt64StartingAtPut9' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
	self at: index+8 put: value9.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 [

	<primitive: 'primitiveInt64StartingAtPut10' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
	self at: index+8 put: value9.
	self at: index+9 put: value10.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 [

	<primitive: 'primitiveInt64StartingAtPut11' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
	self at: index+8 put: value9.
	self at: index+9 put: value10.
	self at: index+10 put: value11.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 put: value12 [

	<primitive: 'primitiveInt64StartingAtPut12' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
	self at: index+8 put: value9.
	self at: index+9 put: value10.
	self at: index+10 put: value11.
	self at: index+11 put: value12.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 put: value12 put: value13 [

	<primitive: 'primitiveInt64StartingAtPut13' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
	self at: index+8 put: value9.
	self at: index+9 put: value10.
	self at: index+10 put: value11.
	self at: index+11 put: value12.
	self at: index+12 put: value13.
]

{
	#category : #'*RawBitsBulkPlugins-Primitives',
	#'squeak_changestamp' : 'stlu 4/20/2022 17:13'
}
SignedDoubleWordArray >> startingAt: index put: value1 put: value2 put: value3 put: value4 put: value5 put: value6 put: value7 put: value8 put: value9 put: value10 put: value11 put: value12 put: value13 put: value14 [

	<primitive: 'primitiveInt64StartingAtPut14' module: 'ArrayBulkPlugin'>
	self at: index put: value1.
	self at: index+1 put: value2.
	self at: index+2 put: value3.
	self at: index+3 put: value4.
	self at: index+4 put: value5.
	self at: index+5 put: value6.
	self at: index+6 put: value7.
	self at: index+7 put: value8.
	self at: index+8 put: value9.
	self at: index+9 put: value10.
	self at: index+10 put: value11.
	self at: index+11 put: value12.
	self at: index+12 put: value13.
	self at: index+13 put: value14.
]
