as yet unclassified
vkCmdTraceRaysNV: commandBuffer with: raygenShaderBindingTableBuffer with: raygenShaderBindingOffset with: missShaderBindingTableBuffer with: missShaderBindingOffset with: missShaderBindingStride with: hitShaderBindingTableBuffer with: hitShaderBindingOffset with: hitShaderBindingStride with: callableShaderBindingTableBuffer with: callableShaderBindingOffset with: callableShaderBindingStride with: width with: height with: depth

	<apicall: void 'vkCmdTraceRaysNV' (VkCommandBuffer VkBuffer VkDeviceSize VkBuffer VkDeviceSize VkDeviceSize VkBuffer VkDeviceSize VkDeviceSize VkBuffer VkDeviceSize VkDeviceSize uint32_t uint32_t uint32_t)>
	^ self externalCallFailed