as yet unclassified
vkCmdBuildAccelerationStructureNV: commandBuffer with: pInfo with: instanceData with: instanceOffset with: update with: dst with: src with: scratch with: scratchOffset

	<apicall: void 'vkCmdBuildAccelerationStructureNV' (VkCommandBuffer VkAccelerationStructureInfoNV* VkBuffer VkDeviceSize VkBool32 VkAccelerationStructureKHR VkAccelerationStructureKHR VkBuffer VkDeviceSize)>
	^ self externalCallFailed