as yet unclassified
vkCmdTraceRaysIndirectKHR: commandBuffer with: pRaygenShaderBindingTable with: pMissShaderBindingTable with: pHitShaderBindingTable with: pCallableShaderBindingTable with: buffer with: offset

	<apicall: void 'vkCmdTraceRaysIndirectKHR' (VkCommandBuffer VkStridedBufferRegionKHR* VkStridedBufferRegionKHR* VkStridedBufferRegionKHR* VkStridedBufferRegionKHR* VkBuffer VkDeviceSize)>
	^ self externalCallFailed