as yet unclassified
vkCmdTraceRaysKHR: commandBuffer with: pRaygenShaderBindingTable with: pMissShaderBindingTable with: pHitShaderBindingTable with: pCallableShaderBindingTable with: width with: height with: depth

	<apicall: void 'vkCmdTraceRaysKHR' (VkCommandBuffer VkStridedBufferRegionKHR* VkStridedBufferRegionKHR* VkStridedBufferRegionKHR* VkStridedBufferRegionKHR* uint32_t uint32_t uint32_t)>
	^ self externalCallFailed