as yet unclassified
vkGetPhysicalDeviceSparseImageFormatProperties: physicalDevice with: format with: type with: samples with: usage with: tiling with: pPropertyCount with: pProperties

	<apicall: void 'vkGetPhysicalDeviceSparseImageFormatProperties' (VkPhysicalDevice VkFormat VkImageType VkSampleCountFlagBits VkImageUsageFlags VkImageTiling uint32_t* VkSparseImageFormatProperties*)>
	^ self externalCallFailed