as yet unclassified
fields

	^ #(
		(sType 'VkStructureType')
		(pNext 'void*')
		(flags 'VkDescriptorUpdateTemplateCreateFlags')
		(descriptorUpdateEntryCount 'uint32_t')
		(pDescriptorUpdateEntries 'VkDescriptorUpdateTemplateEntry*')
		(templateType 'VkDescriptorUpdateTemplateType')
		(descriptorSetLayout 'VkDescriptorSetLayout')
		(pipelineBindPoint 'VkPipelineBindPoint')
		(pipelineLayout 'VkPipelineLayout')
		(set 'uint32_t')
	)