Class {
	#name : #VkAccelerationStructureBuildTypeKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkAccelerationStructureBuildTypeKHR class >> VK_ACCELERATION_STRUCTURE_BUILD_TYPE_DEVICE_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureBuildTypeKHR class >> VK_ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureBuildTypeKHR class >> VK_ACCELERATION_STRUCTURE_BUILD_TYPE_HOST_OR_DEVICE_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureBuildTypeKHR class >> originalTypeName [

    ^ 'long'
]
