Class {
	#name : #VkAccelerationStructureTypeKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkAccelerationStructureTypeKHR class >> VK_ACCELERATION_STRUCTURE_TYPE_BOTTOM_LEVEL_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureTypeKHR class >> VK_ACCELERATION_STRUCTURE_TYPE_TOP_LEVEL_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureTypeKHR class >> originalTypeName [

    ^ 'long'
]
