Class {
	#name : #VkAccelerationStructureMemoryRequirementsTypeKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkAccelerationStructureMemoryRequirementsTypeKHR class >> VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_BUILD_SCRATCH_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureMemoryRequirementsTypeKHR class >> VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_OBJECT_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureMemoryRequirementsTypeKHR class >> VK_ACCELERATION_STRUCTURE_MEMORY_REQUIREMENTS_TYPE_UPDATE_SCRATCH_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkAccelerationStructureMemoryRequirementsTypeKHR class >> originalTypeName [

    ^ 'long'
]
