Class {
	#name : #VkAttachmentStoreOp,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkAttachmentStoreOp class >> VK_ATTACHMENT_STORE_OP_DONT_CARE [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkAttachmentStoreOp class >> VK_ATTACHMENT_STORE_OP_STORE [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkAttachmentStoreOp class >> originalTypeName [

    ^ 'long'
]
