Class {
	#name : #VkBlendOverlapEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkBlendOverlapEXT class >> VK_BLEND_OVERLAP_CONJOINT_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkBlendOverlapEXT class >> VK_BLEND_OVERLAP_DISJOINT_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkBlendOverlapEXT class >> VK_BLEND_OVERLAP_UNCORRELATED_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkBlendOverlapEXT class >> originalTypeName [

    ^ 'long'
]
