Class {
	#name : #VkBlendOp,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkBlendOp class >> VK_BLEND_OP_ADD [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkBlendOp class >> VK_BLEND_OP_MAX [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkBlendOp class >> VK_BLEND_OP_MIN [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkBlendOp class >> VK_BLEND_OP_REVERSE_SUBTRACT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkBlendOp class >> VK_BLEND_OP_SUBTRACT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkBlendOp class >> originalTypeName [

    ^ 'long'
]
