Class {
	#name : #VkColorSpaceKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkColorSpaceKHR class >> VK_COLORSPACE_SRGB_NONLINEAR_KHR [

	^ self on: (self VK_COLOR_SPACE_SRGB_NONLINEAR_KHR)
]

{ #category : #'as yet unclassified' }
VkColorSpaceKHR class >> VK_COLOR_SPACE_SRGB_NONLINEAR_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkColorSpaceKHR class >> originalTypeName [

    ^ 'long'
]
