Class {
	#name : #VkCopyAccelerationStructureModeKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkCopyAccelerationStructureModeKHR class >> VK_COPY_ACCELERATION_STRUCTURE_MODE_CLONE_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkCopyAccelerationStructureModeKHR class >> VK_COPY_ACCELERATION_STRUCTURE_MODE_COMPACT_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkCopyAccelerationStructureModeKHR class >> VK_COPY_ACCELERATION_STRUCTURE_MODE_DESERIALIZE_KHR [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkCopyAccelerationStructureModeKHR class >> VK_COPY_ACCELERATION_STRUCTURE_MODE_SERIALIZE_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkCopyAccelerationStructureModeKHR class >> originalTypeName [

    ^ 'long'
]
