Class {
	#name : #VkConservativeRasterizationModeEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkConservativeRasterizationModeEXT class >> VK_CONSERVATIVE_RASTERIZATION_MODE_DISABLED_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkConservativeRasterizationModeEXT class >> VK_CONSERVATIVE_RASTERIZATION_MODE_OVERESTIMATE_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkConservativeRasterizationModeEXT class >> VK_CONSERVATIVE_RASTERIZATION_MODE_UNDERESTIMATE_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkConservativeRasterizationModeEXT class >> originalTypeName [

    ^ 'long'
]
