Class {
	#name : #VkComponentSwizzle,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_A [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_B [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_G [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_IDENTITY [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_ONE [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_R [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> VK_COMPONENT_SWIZZLE_ZERO [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkComponentSwizzle class >> originalTypeName [

    ^ 'long'
]
