Class {
	#name : #VkDebugReportObjectTypeEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_EXT [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_BUFFER_VIEW_EXT [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_BUFFER_EXT [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_COMMAND_POOL_EXT [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_EXT [

	^ self on: (self VK_DEBUG_REPORT_OBJECT_TYPE_DEBUG_REPORT_CALLBACK_EXT_EXT)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_POOL_EXT [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_EXT [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DESCRIPTOR_SET_LAYOUT_EXT [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DEVICE_MEMORY_EXT [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_KHR_EXT [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_DISPLAY_MODE_KHR_EXT [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_EVENT_EXT [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_FENCE_EXT [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_FRAMEBUFFER_EXT [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_EXT [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_IMAGE_VIEW_EXT [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_INSTANCE_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_PHYSICAL_DEVICE_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_CACHE_EXT [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_EXT [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_PIPELINE_LAYOUT_EXT [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_QUERY_POOL_EXT [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_QUEUE_EXT [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_RENDER_PASS_EXT [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_SAMPLER_EXT [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_SEMAPHORE_EXT [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_SHADER_MODULE_EXT [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_SURFACE_KHR_EXT [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_SWAPCHAIN_KHR_EXT [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_UNKNOWN_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT [

	^ self on: (self VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> VK_DEBUG_REPORT_OBJECT_TYPE_VALIDATION_CACHE_EXT_EXT [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
VkDebugReportObjectTypeEXT class >> originalTypeName [

    ^ 'long'
]
