Class {
	#name : #VkDisplayPowerStateEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkDisplayPowerStateEXT class >> VK_DISPLAY_POWER_STATE_OFF_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkDisplayPowerStateEXT class >> VK_DISPLAY_POWER_STATE_ON_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkDisplayPowerStateEXT class >> VK_DISPLAY_POWER_STATE_SUSPEND_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkDisplayPowerStateEXT class >> originalTypeName [

    ^ 'long'
]
