Class {
	#name : #VkDiscardRectangleModeEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkDiscardRectangleModeEXT class >> VK_DISCARD_RECTANGLE_MODE_EXCLUSIVE_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkDiscardRectangleModeEXT class >> VK_DISCARD_RECTANGLE_MODE_INCLUSIVE_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkDiscardRectangleModeEXT class >> originalTypeName [

    ^ 'long'
]
