Class {
	#name : #VkDynamicState,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_BLEND_CONSTANTS [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_DEPTH_BIAS [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_DEPTH_BOUNDS [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_LINE_WIDTH [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_SCISSOR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_STENCIL_COMPARE_MASK [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_STENCIL_REFERENCE [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_STENCIL_WRITE_MASK [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> VK_DYNAMIC_STATE_VIEWPORT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkDynamicState class >> originalTypeName [

    ^ 'long'
]
