Class {
	#name : #VkFormat,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A1R5G5B5_UNORM_PACK16 [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2B10G10R10_SINT_PACK32 [

	^ self on: (69)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2B10G10R10_SNORM_PACK32 [

	^ self on: (65)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2B10G10R10_SSCALED_PACK32 [

	^ self on: (67)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2B10G10R10_UINT_PACK32 [

	^ self on: (68)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2B10G10R10_UNORM_PACK32 [

	^ self on: (64)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2B10G10R10_USCALED_PACK32 [

	^ self on: (66)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2R10G10B10_SINT_PACK32 [

	^ self on: (63)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2R10G10B10_SNORM_PACK32 [

	^ self on: (59)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2R10G10B10_SSCALED_PACK32 [

	^ self on: (61)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2R10G10B10_UINT_PACK32 [

	^ self on: (62)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2R10G10B10_UNORM_PACK32 [

	^ self on: (58)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A2R10G10B10_USCALED_PACK32 [

	^ self on: (60)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_SINT_PACK32 [

	^ self on: (56)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_SNORM_PACK32 [

	^ self on: (52)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_SRGB_PACK32 [

	^ self on: (57)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_SSCALED_PACK32 [

	^ self on: (54)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_UINT_PACK32 [

	^ self on: (55)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_UNORM_PACK32 [

	^ self on: (51)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_A8B8G8R8_USCALED_PACK32 [

	^ self on: (53)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x10_SRGB_BLOCK [

	^ self on: (180)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x10_UNORM_BLOCK [

	^ self on: (179)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x5_SRGB_BLOCK [

	^ self on: (174)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x5_UNORM_BLOCK [

	^ self on: (173)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x6_SRGB_BLOCK [

	^ self on: (176)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x6_UNORM_BLOCK [

	^ self on: (175)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x8_SRGB_BLOCK [

	^ self on: (178)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_10x8_UNORM_BLOCK [

	^ self on: (177)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_12x10_SRGB_BLOCK [

	^ self on: (182)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_12x10_UNORM_BLOCK [

	^ self on: (181)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_12x12_SRGB_BLOCK [

	^ self on: (184)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_12x12_UNORM_BLOCK [

	^ self on: (183)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_4x4_SRGB_BLOCK [

	^ self on: (158)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_4x4_UNORM_BLOCK [

	^ self on: (157)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_5x4_SRGB_BLOCK [

	^ self on: (160)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_5x4_UNORM_BLOCK [

	^ self on: (159)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_5x5_SRGB_BLOCK [

	^ self on: (162)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_5x5_UNORM_BLOCK [

	^ self on: (161)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_6x5_SRGB_BLOCK [

	^ self on: (164)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_6x5_UNORM_BLOCK [

	^ self on: (163)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_6x6_SRGB_BLOCK [

	^ self on: (166)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_6x6_UNORM_BLOCK [

	^ self on: (165)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_8x5_SRGB_BLOCK [

	^ self on: (168)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_8x5_UNORM_BLOCK [

	^ self on: (167)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_8x6_SRGB_BLOCK [

	^ self on: (170)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_8x6_UNORM_BLOCK [

	^ self on: (169)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_8x8_SRGB_BLOCK [

	^ self on: (172)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ASTC_8x8_UNORM_BLOCK [

	^ self on: (171)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B10G11R11_UFLOAT_PACK32 [

	^ self on: (122)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B4G4R4A4_UNORM_PACK16 [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B5G5R5A1_UNORM_PACK16 [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B5G6R5_UNORM_PACK16 [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_SINT [

	^ self on: (49)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_SNORM [

	^ self on: (45)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_SRGB [

	^ self on: (50)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_SSCALED [

	^ self on: (47)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_UINT [

	^ self on: (48)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_UNORM [

	^ self on: (44)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8A8_USCALED [

	^ self on: (46)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_SINT [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_SNORM [

	^ self on: (31)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_SRGB [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_SSCALED [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_UINT [

	^ self on: (34)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_UNORM [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_B8G8R8_USCALED [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC1_RGBA_SRGB_BLOCK [

	^ self on: (134)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC1_RGBA_UNORM_BLOCK [

	^ self on: (133)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC1_RGB_SRGB_BLOCK [

	^ self on: (132)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC1_RGB_UNORM_BLOCK [

	^ self on: (131)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC2_SRGB_BLOCK [

	^ self on: (136)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC2_UNORM_BLOCK [

	^ self on: (135)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC3_SRGB_BLOCK [

	^ self on: (138)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC3_UNORM_BLOCK [

	^ self on: (137)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC4_SNORM_BLOCK [

	^ self on: (140)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC4_UNORM_BLOCK [

	^ self on: (139)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC5_SNORM_BLOCK [

	^ self on: (142)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC5_UNORM_BLOCK [

	^ self on: (141)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC6H_SFLOAT_BLOCK [

	^ self on: (144)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC6H_UFLOAT_BLOCK [

	^ self on: (143)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC7_SRGB_BLOCK [

	^ self on: (146)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_BC7_UNORM_BLOCK [

	^ self on: (145)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_D16_UNORM [

	^ self on: (124)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_D16_UNORM_S8_UINT [

	^ self on: (128)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_D24_UNORM_S8_UINT [

	^ self on: (129)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_D32_SFLOAT [

	^ self on: (126)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_D32_SFLOAT_S8_UINT [

	^ self on: (130)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_E5B9G9R9_UFLOAT_PACK32 [

	^ self on: (123)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_EAC_R11G11_SNORM_BLOCK [

	^ self on: (156)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_EAC_R11G11_UNORM_BLOCK [

	^ self on: (155)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_EAC_R11_SNORM_BLOCK [

	^ self on: (154)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_EAC_R11_UNORM_BLOCK [

	^ self on: (153)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK [

	^ self on: (150)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK [

	^ self on: (149)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK [

	^ self on: (152)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK [

	^ self on: (151)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK [

	^ self on: (148)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK [

	^ self on: (147)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_SFLOAT [

	^ self on: (97)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_SINT [

	^ self on: (96)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_SNORM [

	^ self on: (92)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_SSCALED [

	^ self on: (94)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_UINT [

	^ self on: (95)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_UNORM [

	^ self on: (91)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16A16_USCALED [

	^ self on: (93)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_SFLOAT [

	^ self on: (90)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_SINT [

	^ self on: (89)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_SNORM [

	^ self on: (85)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_SSCALED [

	^ self on: (87)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_UINT [

	^ self on: (88)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_UNORM [

	^ self on: (84)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16B16_USCALED [

	^ self on: (86)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_SFLOAT [

	^ self on: (83)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_SINT [

	^ self on: (82)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_SNORM [

	^ self on: (78)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_SSCALED [

	^ self on: (80)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_UINT [

	^ self on: (81)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_UNORM [

	^ self on: (77)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16G16_USCALED [

	^ self on: (79)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_SFLOAT [

	^ self on: (76)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_SINT [

	^ self on: (75)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_SNORM [

	^ self on: (71)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_SSCALED [

	^ self on: (73)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_UINT [

	^ self on: (74)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_UNORM [

	^ self on: (70)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R16_USCALED [

	^ self on: (72)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32B32A32_SFLOAT [

	^ self on: (109)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32B32A32_SINT [

	^ self on: (108)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32B32A32_UINT [

	^ self on: (107)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32B32_SFLOAT [

	^ self on: (106)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32B32_SINT [

	^ self on: (105)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32B32_UINT [

	^ self on: (104)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32_SFLOAT [

	^ self on: (103)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32_SINT [

	^ self on: (102)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32G32_UINT [

	^ self on: (101)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32_SFLOAT [

	^ self on: (100)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32_SINT [

	^ self on: (99)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R32_UINT [

	^ self on: (98)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R4G4B4A4_UNORM_PACK16 [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R4G4_UNORM_PACK8 [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R5G5B5A1_UNORM_PACK16 [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R5G6B5_UNORM_PACK16 [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64B64A64_SFLOAT [

	^ self on: (121)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64B64A64_SINT [

	^ self on: (120)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64B64A64_UINT [

	^ self on: (119)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64B64_SFLOAT [

	^ self on: (118)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64B64_SINT [

	^ self on: (117)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64B64_UINT [

	^ self on: (116)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64_SFLOAT [

	^ self on: (115)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64_SINT [

	^ self on: (114)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64G64_UINT [

	^ self on: (113)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64_SFLOAT [

	^ self on: (112)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64_SINT [

	^ self on: (111)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R64_UINT [

	^ self on: (110)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_SINT [

	^ self on: (42)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_SNORM [

	^ self on: (38)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_SRGB [

	^ self on: (43)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_SSCALED [

	^ self on: (40)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_UINT [

	^ self on: (41)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_UNORM [

	^ self on: (37)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8A8_USCALED [

	^ self on: (39)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_SINT [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_SNORM [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_SRGB [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_SSCALED [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_UINT [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_UNORM [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8B8_USCALED [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_SINT [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_SNORM [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_SRGB [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_SSCALED [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_UINT [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_UNORM [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8G8_USCALED [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_SINT [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_SNORM [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_SRGB [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_SSCALED [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_UINT [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_UNORM [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_R8_USCALED [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_S8_UINT [

	^ self on: (127)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_UNDEFINED [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkFormat class >> VK_FORMAT_X8_D24_UNORM_PACK32 [

	^ self on: (125)
]

{ #category : #'as yet unclassified' }
VkFormat class >> originalTypeName [

    ^ 'long'
]
