Class {
	#name : #VkFullScreenExclusiveEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkFullScreenExclusiveEXT class >> VK_FULL_SCREEN_EXCLUSIVE_ALLOWED_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkFullScreenExclusiveEXT class >> VK_FULL_SCREEN_EXCLUSIVE_APPLICATION_CONTROLLED_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkFullScreenExclusiveEXT class >> VK_FULL_SCREEN_EXCLUSIVE_DEFAULT_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkFullScreenExclusiveEXT class >> VK_FULL_SCREEN_EXCLUSIVE_DISALLOWED_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkFullScreenExclusiveEXT class >> originalTypeName [

    ^ 'long'
]
