Class {
	#name : #VkImageViewType,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_1D [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_1D_ARRAY [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_2D [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_2D_ARRAY [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_3D [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_CUBE [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> VK_IMAGE_VIEW_TYPE_CUBE_ARRAY [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkImageViewType class >> originalTypeName [

    ^ 'long'
]
