Class {
	#name : #VkIndexType,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkIndexType class >> VK_INDEX_TYPE_UINT16 [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkIndexType class >> VK_INDEX_TYPE_UINT32 [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkIndexType class >> originalTypeName [

    ^ 'long'
]
