Class {
	#name : #VkLineRasterizationModeEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkLineRasterizationModeEXT class >> VK_LINE_RASTERIZATION_MODE_BRESENHAM_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkLineRasterizationModeEXT class >> VK_LINE_RASTERIZATION_MODE_DEFAULT_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkLineRasterizationModeEXT class >> VK_LINE_RASTERIZATION_MODE_RECTANGULAR_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkLineRasterizationModeEXT class >> VK_LINE_RASTERIZATION_MODE_RECTANGULAR_SMOOTH_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkLineRasterizationModeEXT class >> originalTypeName [

    ^ 'long'
]
