Class {
	#name : #VkLogicOp,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_AND [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_AND_INVERTED [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_AND_REVERSE [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_CLEAR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_COPY [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_COPY_INVERTED [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_EQUIVALENT [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_INVERT [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_NAND [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_NOR [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_NO_OP [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_OR [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_OR_INVERTED [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_OR_REVERSE [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_SET [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> VK_LOGIC_OP_XOR [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkLogicOp class >> originalTypeName [

    ^ 'long'
]
