Class {
	#name : #VkPerformanceParameterTypeINTEL,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPerformanceParameterTypeINTEL class >> VK_PERFORMANCE_PARAMETER_TYPE_HW_COUNTERS_SUPPORTED_INTEL [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPerformanceParameterTypeINTEL class >> VK_PERFORMANCE_PARAMETER_TYPE_STREAM_MARKER_VALID_BITS_INTEL [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPerformanceParameterTypeINTEL class >> originalTypeName [

    ^ 'long'
]
