Class {
	#name : #VkPerformanceCounterUnitKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_AMPS_KHR [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_BYTES_KHR [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_BYTES_PER_SECOND_KHR [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_CYCLES_KHR [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_GENERIC_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_HERTZ_KHR [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_KELVIN_KHR [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_NANOSECONDS_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_PERCENTAGE_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_VOLTS_KHR [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> VK_PERFORMANCE_COUNTER_UNIT_WATTS_KHR [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterUnitKHR class >> originalTypeName [

    ^ 'long'
]
