Class {
	#name : #VkPerformanceConfigurationTypeINTEL,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPerformanceConfigurationTypeINTEL class >> VK_PERFORMANCE_CONFIGURATION_TYPE_COMMAND_QUEUE_METRICS_DISCOVERY_ACTIVATED_INTEL [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPerformanceConfigurationTypeINTEL class >> originalTypeName [

    ^ 'long'
]
