Class {
	#name : #VkPerformanceCounterStorageKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> VK_PERFORMANCE_COUNTER_STORAGE_FLOAT32_KHR [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> VK_PERFORMANCE_COUNTER_STORAGE_FLOAT64_KHR [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> VK_PERFORMANCE_COUNTER_STORAGE_INT32_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> VK_PERFORMANCE_COUNTER_STORAGE_INT64_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> VK_PERFORMANCE_COUNTER_STORAGE_UINT32_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> VK_PERFORMANCE_COUNTER_STORAGE_UINT64_KHR [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkPerformanceCounterStorageKHR class >> originalTypeName [

    ^ 'long'
]
