Class {
	#name : #VkPerformanceOverrideTypeINTEL,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPerformanceOverrideTypeINTEL class >> VK_PERFORMANCE_OVERRIDE_TYPE_FLUSH_GPU_CACHES_INTEL [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPerformanceOverrideTypeINTEL class >> VK_PERFORMANCE_OVERRIDE_TYPE_NULL_HARDWARE_INTEL [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPerformanceOverrideTypeINTEL class >> originalTypeName [

    ^ 'long'
]
