Class {
	#name : #VkPipelineExecutableStatisticFormatKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPipelineExecutableStatisticFormatKHR class >> VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_BOOL32_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPipelineExecutableStatisticFormatKHR class >> VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_FLOAT64_KHR [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkPipelineExecutableStatisticFormatKHR class >> VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_INT64_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPipelineExecutableStatisticFormatKHR class >> VK_PIPELINE_EXECUTABLE_STATISTIC_FORMAT_UINT64_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkPipelineExecutableStatisticFormatKHR class >> originalTypeName [

    ^ 'long'
]
