Class {
	#name : #VkPolygonMode,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPolygonMode class >> VK_POLYGON_MODE_FILL [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPolygonMode class >> VK_POLYGON_MODE_LINE [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPolygonMode class >> VK_POLYGON_MODE_POINT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkPolygonMode class >> originalTypeName [

    ^ 'long'
]
