Class {
	#name : #VkPrimitiveTopology,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_LINE_LIST [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_LINE_LIST_WITH_ADJACENCY [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_LINE_STRIP [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_LINE_STRIP_WITH_ADJACENCY [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_PATCH_LIST [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_POINT_LIST [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_TRIANGLE_FAN [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_TRIANGLE_LIST_WITH_ADJACENCY [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> VK_PRIMITIVE_TOPOLOGY_TRIANGLE_STRIP_WITH_ADJACENCY [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
VkPrimitiveTopology class >> originalTypeName [

    ^ 'long'
]
