Class {
	#name : #VkRayTracingShaderGroupTypeKHR,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkRayTracingShaderGroupTypeKHR class >> VK_RAY_TRACING_SHADER_GROUP_TYPE_GENERAL_KHR [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkRayTracingShaderGroupTypeKHR class >> VK_RAY_TRACING_SHADER_GROUP_TYPE_PROCEDURAL_HIT_GROUP_KHR [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkRayTracingShaderGroupTypeKHR class >> VK_RAY_TRACING_SHADER_GROUP_TYPE_TRIANGLES_HIT_GROUP_KHR [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkRayTracingShaderGroupTypeKHR class >> originalTypeName [

    ^ 'long'
]
