Class {
	#name : #VkSamplerYcbcrRange,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkSamplerYcbcrRange class >> VK_SAMPLER_YCBCR_RANGE_ITU_FULL [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrRange class >> VK_SAMPLER_YCBCR_RANGE_ITU_NARROW [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrRange class >> originalTypeName [

    ^ 'long'
]
