Class {
	#name : #VkSamplerYcbcrModelConversion,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkSamplerYcbcrModelConversion class >> VK_SAMPLER_YCBCR_MODEL_CONVERSION_RGB_IDENTITY [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrModelConversion class >> VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_2020 [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrModelConversion class >> VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_601 [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrModelConversion class >> VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_709 [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrModelConversion class >> VK_SAMPLER_YCBCR_MODEL_CONVERSION_YCBCR_IDENTITY [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkSamplerYcbcrModelConversion class >> originalTypeName [

    ^ 'long'
]
