Class {
	#name : #VkScopeNV,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkScopeNV class >> VK_SCOPE_DEVICE_NV [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkScopeNV class >> VK_SCOPE_QUEUE_FAMILY_NV [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkScopeNV class >> VK_SCOPE_SUBGROUP_NV [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkScopeNV class >> VK_SCOPE_WORKGROUP_NV [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkScopeNV class >> originalTypeName [

    ^ 'long'
]
