Class {
	#name : #VkShaderFloatControlsIndependence,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkShaderFloatControlsIndependence class >> VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_32_BIT_ONLY [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkShaderFloatControlsIndependence class >> VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_ALL [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkShaderFloatControlsIndependence class >> VK_SHADER_FLOAT_CONTROLS_INDEPENDENCE_NONE [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkShaderFloatControlsIndependence class >> originalTypeName [

    ^ 'long'
]
