Class {
	#name : #VkStructureType,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_ACQUIRE_NEXT_IMAGE_INFO_KHR [

	^ self on: (1000060010)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_APPLICATION_INFO [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_BIND_IMAGE_MEMORY_SWAPCHAIN_INFO_KHR [

	^ self on: (1000060009)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_BIND_SPARSE_INFO [

	^ self on: (7)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO [

	^ self on: (12)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER [

	^ self on: (44)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_BUFFER_VIEW_CREATE_INFO [

	^ self on: (13)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO [

	^ self on: (40)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO [

	^ self on: (42)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO [

	^ self on: (41)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO [

	^ self on: (39)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_COMPUTE_PIPELINE_CREATE_INFO [

	^ self on: (29)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_COPY_DESCRIPTOR_SET [

	^ self on: (36)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEBUG_UTILS_LABEL_EXT [

	^ self on: (1000128002)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT [

	^ self on: (1000128003)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT [

	^ self on: (1000128004)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT [

	^ self on: (1000128000)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEBUG_UTILS_OBJECT_TAG_INFO_EXT [

	^ self on: (1000128001)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DESCRIPTOR_POOL_CREATE_INFO [

	^ self on: (33)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO [

	^ self on: (34)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO [

	^ self on: (32)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_CAPABILITIES_KHR [

	^ self on: (1000060007)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEVICE_GROUP_PRESENT_INFO_KHR [

	^ self on: (1000060011)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEVICE_GROUP_SWAPCHAIN_CREATE_INFO_KHR [

	^ self on: (1000060012)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_EVENT_CREATE_INFO [

	^ self on: (10)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_FENCE_CREATE_INFO [

	^ self on: (8)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO [

	^ self on: (37)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_GRAPHICS_PIPELINE_CREATE_INFO [

	^ self on: (28)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO [

	^ self on: (14)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER [

	^ self on: (45)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_IMAGE_SWAPCHAIN_CREATE_INFO_KHR [

	^ self on: (1000060008)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO [

	^ self on: (15)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_LOADER_DEVICE_CREATE_INFO [

	^ self on: (48)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_LOADER_INSTANCE_CREATE_INFO [

	^ self on: (47)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE [

	^ self on: (6)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO [

	^ self on: (5)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_MEMORY_BARRIER [

	^ self on: (46)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO [

	^ self on: (17)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO [

	^ self on: (26)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO [

	^ self on: (25)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_DYNAMIC_STATE_CREATE_INFO [

	^ self on: (27)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO [

	^ self on: (20)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO [

	^ self on: (30)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_MULTISAMPLE_STATE_CREATE_INFO [

	^ self on: (24)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO [

	^ self on: (23)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_SHADER_STAGE_CREATE_INFO [

	^ self on: (18)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_TESSELLATION_STATE_CREATE_INFO [

	^ self on: (21)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO [

	^ self on: (19)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO [

	^ self on: (22)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_PRESENT_INFO_KHR [

	^ self on: (1000001001)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_QUERY_POOL_CREATE_INFO [

	^ self on: (11)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO [

	^ self on: (43)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO [

	^ self on: (38)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO [

	^ self on: (31)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_SEMAPHORE_CREATE_INFO [

	^ self on: (9)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_SHADER_MODULE_CREATE_INFO [

	^ self on: (16)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_SUBMIT_INFO [

	^ self on: (4)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR [

	^ self on: (1000001000)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET [

	^ self on: (35)
]

{ #category : #'as yet unclassified' }
VkStructureType class >> originalTypeName [

    ^ 'long'
]
