Class {
	#name : #VkSubpassContents,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkSubpassContents class >> VK_SUBPASS_CONTENTS_INLINE [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkSubpassContents class >> VK_SUBPASS_CONTENTS_SECONDARY_COMMAND_BUFFERS [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkSubpassContents class >> originalTypeName [

    ^ 'long'
]
