Class {
	#name : #VkTessellationDomainOrigin,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkTessellationDomainOrigin class >> VK_TESSELLATION_DOMAIN_ORIGIN_LOWER_LEFT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkTessellationDomainOrigin class >> VK_TESSELLATION_DOMAIN_ORIGIN_UPPER_LEFT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkTessellationDomainOrigin class >> originalTypeName [

    ^ 'long'
]
