Class {
	#name : #VkTimeDomainEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkTimeDomainEXT class >> VK_TIME_DOMAIN_CLOCK_MONOTONIC_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkTimeDomainEXT class >> VK_TIME_DOMAIN_CLOCK_MONOTONIC_RAW_EXT [

	^ self on: (2)
]

{ #category : #'as yet unclassified' }
VkTimeDomainEXT class >> VK_TIME_DOMAIN_DEVICE_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkTimeDomainEXT class >> VK_TIME_DOMAIN_QUERY_PERFORMANCE_COUNTER_EXT [

	^ self on: (3)
]

{ #category : #'as yet unclassified' }
VkTimeDomainEXT class >> originalTypeName [

    ^ 'long'
]
