Class {
	#name : #VkValidationCheckEXT,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkValidationCheckEXT class >> VK_VALIDATION_CHECK_ALL_EXT [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkValidationCheckEXT class >> VK_VALIDATION_CHECK_SHADERS_EXT [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkValidationCheckEXT class >> originalTypeName [

    ^ 'long'
]
