Class {
	#name : #VkVertexInputRate,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkVertexInputRate class >> VK_VERTEX_INPUT_RATE_INSTANCE [

	^ self on: (1)
]

{ #category : #'as yet unclassified' }
VkVertexInputRate class >> VK_VERTEX_INPUT_RATE_VERTEX [

	^ self on: (0)
]

{ #category : #'as yet unclassified' }
VkVertexInputRate class >> originalTypeName [

    ^ 'long'
]
