Class {
	#name : #VkVendorId,
	#superclass : #ExternalTypeAlias,
	#category : #'Vulkan-Generated'
}

{ #category : #'as yet unclassified' }
VkVendorId class >> VK_VENDOR_ID_CODEPLAY [

	^ self on: (0x10004)
]

{ #category : #'as yet unclassified' }
VkVendorId class >> VK_VENDOR_ID_KAZAN [

	^ self on: (0x10003)
]

{ #category : #'as yet unclassified' }
VkVendorId class >> VK_VENDOR_ID_MESA [

	^ self on: (0x10005)
]

{ #category : #'as yet unclassified' }
VkVendorId class >> VK_VENDOR_ID_VIV [

	^ self on: (0x10001)
]

{ #category : #'as yet unclassified' }
VkVendorId class >> VK_VENDOR_ID_VSI [

	^ self on: (0x10002)
]

{ #category : #'as yet unclassified' }
VkVendorId class >> originalTypeName [

    ^ 'long'
]
