as yet unclassified
glCopyImageSubData: srcName with: srcTarget with: srcLevel with: srcX with: srcY with: srcZ with: dstName with: dstTarget with: dstLevel with: dstX with: dstY with: dstZ with: srcWidth with: srcHeight with: srcDepth

	<apicall: void 'glCopyImageSubData' (ulong ulong long long long long ulong ulong long long long long long long long) module: 'libGL.so'>
	^ self externalCallFailed