name: 'Create bundle'

on: [push, workflow_dispatch]

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: LinqLover/create-image@master
        id: create-image
        with:
          prepare-script: ./scripts/prepareImage.st
      - uses: actions/upload-artifact@master
        with:
          name: image
          path: ${{ steps.create-image.outputs.bundle-path }}
