name: 'Create bundle'

on:
  workflow_dispatch:
    inputs:
      squeak-revision:
        description: Squeak trunk revision
        required: true
        default: '20536'

jobs:
  setup-bundle:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: linux64x64
            bits: 64
            os: ubuntu-latest
            ext: tar.gz
          # - arch: win64x64
          #   bits: 64
          #   os: windows-latest
    
    defaults:
      run:
        shell: bash
    
    env:
      IMAGE_NAME: Squeak6.0alpha-${{ github.event.inputs.squeak-revision }}-${{ matrix.bits }}bit

    steps:
      - uses: actions/checkout@v2

      - name: Download and extract VM
        run: |
          curl -o vm.tar.gz https://github.com/OpenSmalltalk/opensmalltalk-vm/releases/download/latest-build/squeak.cog.spur_${{ matrix.arch }}.tar.gz
          mkdir -p vm
          tar --extract --gzip --file="vm.tar.gz" --directory="vm"
          cd vm/*
          mv * ..
          rm -rf "$(pwd -P)" && cd ..

      - name: Download and extract Squeak image and sources
        run: |
          curl -o squeak.zip http://files.squeak.org/trunk/${{ env.IMAGE_NAME }}/${{ env.IMAGE_NAME }}.zip
          curl -o SqueakV50.sources.gz http://files.squeak.org/sources_files/SqueakV50.sources.gz
          mkdir -p bundle
          unzip -d bundle squeak.zip
          gzip -c -d SqueakV50.sources.gz > bundle/SqueakV50.sources
      
      - name: Run install.st
        working-directory: bundle
        env:
          GITHUB_TOKEN: ${{ secrets.METACELLO_TOKEN }}
        run: ./squeak -vm-display-null -vm-sound-null ${{ env.IMAGE_NAME }}.image ../ci/install.st
      
      - name: Cleanup installation remnants
        working-directory: bundle
        run: rm -rf *.old *.log *-cache *.st || true
      
      - name: Compress bundle
        working-directory: bundle
        run: tar --create --gzip --file="${{ matrix.arch }}-bundle.tar.gz" *
      
      - name: Upload bundle
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.arch }}-bundle
          path: bundle/${{ matrix.arch }}-bundle.tar.gz
