name: 'Create bundle'

on: [push, workflow_dispatch]

jobs:
  create-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: LinqLover/create-image@master
        id: create-image
        with:
          prepare-script: ./scripts/prepareImage.st
      
      - name: Unzip and clean up bundle
        run: |
          unzip -d bundle ${{ steps.create-image.outputs.bundle-path }}
          cd bundle/*.app/Contents/Resources/
          rm -rf *.old *.log *-cache *.st || true
      
      - name: Include GLFW
        run: |
          wget -O glfw-win-64.zip "https://github.com/glfw/glfw/releases/download/3.3.7/glfw-3.3.7.bin.WIN64.zip"
          unzip -d glfw-win-64 glfw-win-64.zip
          SRC=$(find glfw-win-64/**/lib-vc2019/glfw3.dll)
          DEST="bundle/*.app/Contents/Windows-x86_64"
          cp ${SRC} ${DEST}
      
      - name: Rezip bundle
        run: |
          cd bundle
          zip -r squeak-graphics-canvas-bundle .

      - uses: actions/upload-artifact@master
        with:
          name: image
          path: bundle/squeak-graphics-canvas-bundle.zip
